/* =========================================================
   CHAINLAB — LANGUAGE PROVIDER
   Supports:
   English, Setswana, French, Spanish, Portuguese, German,
   Chinese, Arabic, Hindi, Swahili, Japanese and Korean.

   Missing individual keys safely fall back to English so the
   interface never displays the raw translation key.
========================================================= */

"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type Language =
  | "en"
  | "tn"
  | "fr"
  | "es"
  | "pt"
  | "de"
  | "zh"
  | "ar"
  | "hi"
  | "sw"
  | "ja"
  | "ko";

type TranslationDictionary = Record<string, string>;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const LANGUAGE_STORAGE_KEY = "chainlab-language";

const languageLabels: Record<Language, string> = {
  en: "English",
  tn: "Setswana",
  fr: "Français",
  es: "Español",
  pt: "Português",
  de: "Deutsch",
  zh: "中文",
  ar: "العربية",
  hi: "हिन्दी",
  sw: "Kiswahili",
  ja: "日本語",
  ko: "한국어",
};

/* =========================================================
   ENGLISH — SOURCE OF TRUTH
========================================================= */

const en: TranslationDictionary = {
  "nav.blockchain": "BLOCKCHAIN",
  "nav.solana": "SOLANA",
  "nav.memeCoins": "MEME COINS",
  "nav.security": "SECURITY",

  "home.hero.eyebrow": "[ WEB3 EDUCATION ]",
  "home.hero.learn": "LEARN",
  "home.hero.build": "BUILD",
  "home.hero.ownThe": "UNDERSTAND THE",
  "home.hero.future": "FUTURE",
  "home.hero.description":
    "Learn blockchain, Solana, meme coins, tokenomics, and Web3 security through clear, structured lessons designed to build real understanding.",
  "home.hero.startLearning": "START LEARNING",
  "home.hero.exploreTopics": "EXPLORE TOPICS",
  "home.hero.note": "No prior blockchain experience required.",

  "home.overview.kicker": "[ LEARNING OVERVIEW ]",
  "home.overview.title": "Build Understanding, One Concept at a Time.",
  "home.overview.intro":
    "Start with the fundamentals and progressively connect the ideas that make Web3 work.",
  "home.topics.kicker": "[ CORE TOPICS ]",
  "home.topics.intro":
    "Explore the technologies, concepts, and risks that shape the Web3 ecosystem.",

  "home.topic.blockchain.number": "01",
  "home.topic.blockchain.title": "BLOCKCHAIN",
  "home.topic.blockchain.description":
    "Understand distributed ledgers, blocks, transactions, consensus, and how blockchain networks operate.",
  "home.topic.blockchain.link": "LEARN BLOCKCHAIN",

  "home.topic.solana.number": "02",
  "home.topic.solana.title": "SOLANA",
  "home.topic.solana.description":
    "Explore Solana architecture, accounts, programs, transactions, validators, and its ecosystem.",
  "home.topic.solana.link": "LEARN SOLANA",

  "home.topic.memeCoins.number": "03",
  "home.topic.memeCoins.title": "MEME COINS",
  "home.topic.memeCoins.description":
    "Understand tokens, communities, liquidity, tokenomics, market dynamics, and risk.",
  "home.topic.memeCoins.link": "LEARN MEME COINS",

  "home.topic.security.number": "04",
  "home.topic.security.title": "SECURITY",
  "home.topic.security.description":
    "Learn about wallets, private keys, scams, phishing, smart contracts, and responsible Web3 use.",
  "home.topic.security.link": "LEARN SECURITY",

  "home.topic.dapps.number": "05",
  "home.topic.dapps.title": "DAPPS",
  "home.topic.dapps.description":
    "Discover how decentralized applications connect users, smart contracts, wallets, and blockchain networks.",

  "home.understand.number": "01",
  "home.understand.title": "UNDERSTAND",
  "home.understand.description":
    "Discover what a blockchain is, how distributed networks record information, and how blocks, transactions, consensus, and validators relate to one another.",

  "home.explore.number": "02",
  "home.explore.title": "EXPLORE",
  "home.explore.description":
    "Follow the connections between wallets, keys, tokens, smart contracts, decentralized applications, and the networks that support them.",

  "home.practise.number": "03",
  "home.practise.title": "PRACTISE",
  "home.practise.description":
    "Use structured explanations and practical examples to reinforce each topic, check your understanding, and build a foundation for further study.",

  "home.bottom.startCurious": "START CURIOUS.",
  "home.bottom.description":
    "Keep learning at your own pace and build your understanding step by step.",
  "home.bottom.browse": "BROWSE THE LEARNING LIBRARY",

  "home.features.practical.title": "PRACTICAL LEARNING",
  "home.features.practical.description":
    "Step-by-step lessons designed for beginners and future Web3 builders.",
  "home.features.web3.title": "WEB3 FOCUSED",
  "home.features.web3.description":
    "Learn blockchain, Solana, meme coins, tokenomics, and decentralized technologies.",
  "home.features.security.title": "SECURITY AWARE",
  "home.features.security.description":
    "Understand Web3 risks and learn how to protect yourself in the decentralized world.",
  "home.features.community.title": "COMMUNITY READY",
  "home.features.community.description":
    "Build knowledge that can help you participate in the evolving Web3 ecosystem.",

  "home.stats.coreTopics": "CORE TOPICS",
  "home.stats.learningPaths": "LEARNING PATHS",
  "home.stats.access": "ACCESS",

  "home.about.label": "[ ABOUT BIRTHDAY MESSAGING ]",
  "home.about.title": "The Company",
  "home.about.titleSpan": "Behind ChainLab.",
  "home.about.description":
    "ChainLab is an educational initiative created by Birthday Messaging to make blockchain and Web3 technology easier to understand.",
  "home.about.description2":
    "As emerging technologies continue to change the way people build, communicate, transact, and participate online, understanding the technology behind them becomes increasingly important.",
  "home.about.description3":
    "Birthday Messaging created ChainLab as a learning environment where people can explore these concepts progressively — starting with the fundamentals and moving toward more advanced Web3 topics.",
  "home.about.button": "EXPLORE CHAINLAB",
  "home.about.companyLabel": "BIRTHDAY MESSAGING / CHAINLAB",
  "home.about.location": "EDUCATION / TECHNOLOGY / WEB3",

  "home.values.innovation.title": "INNOVATION",
  "home.values.innovation.description":
    "Exploring emerging technologies and the ideas shaping the digital future.",
  "home.values.education.title": "EDUCATION",
  "home.values.education.description":
    "Turning complex technical concepts into practical knowledge people can understand.",
  "home.values.access.title": "ACCESS",
  "home.values.access.description":
    "Making foundational Web3 education available without unnecessary barriers.",

  "home.about.whyTitle": "Web3 Is Changing.",
  "home.about.whyIntro":
    "Blockchain technology is more than cryptocurrency. It introduces new ways of thinking about ownership, digital assets, applications, identity, communities, and online coordination.",

  "home.mission.label": "[ WHY CHAINLAB ]",
  "home.mission.fundamentals.title": "START WITH THE FUNDAMENTALS",
  "home.mission.fundamentals.description":
    "Build a strong understanding of blockchain before moving into more specialized technologies.",
  "home.mission.connection.title": "LEARN BY CONNECTION",
  "home.mission.connection.description":
    "Understand how wallets, networks, transactions, tokens, applications, and users fit together.",
  "home.mission.risks.title": "UNDERSTAND THE RISKS",
  "home.mission.risks.description":
    "Learn why security, verification, responsible research, and user awareness matter in Web3.",
  "home.mission.builder.title": "THINK LIKE A BUILDER",
  "home.mission.builder.description":
    "Move beyond simply using technology and develop the knowledge required to understand how it works.",

  "home.paths.label": "[ EXPLORE OUR LEARNING PATHS ]",
  "home.paths.chooseTopic": "Choose a Topic.",
  "home.paths.startJourney": "Start Your Journey.",
  "home.paths.viewAll": "VIEW ALL MODULES →",
  "home.paths.startModule": "START MODULE →",
  "home.paths.comingSoon": "COMING SOON",

  "home.paths.blockchain.title": "BLOCKCHAIN",
  "home.paths.blockchain.description":
    "Learn the fundamentals of blockchain technology, decentralized networks, transactions, blocks, and validation.",
  "home.paths.solana.title": "SOLANA",
  "home.paths.solana.description":
    "Explore Solana, its architecture, accounts, programs, transactions, validators, and ecosystem.",
  "home.paths.memeCoins.title": "MEME COINS",
  "home.paths.memeCoins.description":
    "Understand tokens, communities, liquidity, tokenomics, market dynamics, and risk.",
  "home.paths.security.title": "WEB3 SECURITY",
  "home.paths.security.description":
    "Learn how wallets, private keys, scams, phishing, smart contracts, and user responsibility connect.",
  "home.paths.tokenomics.title": "TOKENOMICS",
  "home.paths.tokenomics.description":
    "Discover how token supply, distribution, utility, incentives, and market participation influence digital assets.",

  "home.process.label": "[ HOW CHAINLAB WORKS ]",
  "home.process.title": "A Simple Path to",
  "home.process.titleSpan": "Web3 Knowledge.",
  "home.process.choose.title": "CHOOSE",
  "home.process.choose.description":
    "Pick a subject that interests you and start with the fundamentals.",
  "home.process.follow.title": "FOLLOW",
  "home.process.follow.description":
    "Learn through structured explanations designed to make difficult concepts easier to follow.",
  "home.process.connect.title": "CONNECT",
  "home.process.connect.description":
    "Understand how different parts of Web3 technology work together.",
  "home.process.keep.title": "KEEP LEARNING",
  "home.process.keep.description":
    "Continue developing your knowledge as blockchain technology evolves.",

  "home.biggerPicture.label": "[ THE BIGGER PICTURE ]",
  "home.biggerPicture.title1": "A More",
  "home.biggerPicture.title2": "Open,",
  "home.biggerPicture.title3": "Educated",
  "home.biggerPicture.title4": "Web3",
  "home.biggerPicture.title5": "Future.",
  "home.biggerPicture.description":
    "We believe people should be able to understand the technologies they interact with.",
  "home.biggerPicture.description2":
    "Whether you are completely new to blockchain, exploring Solana, researching meme coins, or learning how to protect your digital assets, ChainLab provides a place to build your foundation.",
  "home.biggerPicture.labelBottom": "CHAINLAB EDUCATION",
  "home.biggerPicture.location": "GLOBAL / ONLINE",

  "home.security.label": "[ SECURITY FIRST ]",
  "home.security.title": "Knowledge Is Part",
  "home.security.titleSpan": "of Your Security.",
  "home.security.description":
    "Web3 gives users greater control, but greater control also means greater responsibility.",
  "home.security.description2":
    "Understanding wallets, private keys, transactions, phishing attempts, malicious contracts, scams, and common social-engineering techniques can help users make better decisions.",
  "home.security.button": "LEARN SECURITY →",
  "home.security.imageLabel": "VERIFY BEFORE YOU SIGN",

  "home.learning.label": "[ LEARNING EXPERIENCE ]",
  "home.learning.title": "Built for Curious",
  "home.learning.titleSpan": "Learners.",

  "home.testimonial.beginner.description":
    "ChainLab focuses on explaining the concepts instead of assuming the learner already understands the technology.",
  "home.testimonial.beginner.title": "THE BEGINNER",
  "home.testimonial.beginner.subtitle": "Starting the Web3 journey",

  "home.testimonial.explorer.description":
    "The structured approach makes it easier to connect blockchain fundamentals with technologies such as Solana and token ecosystems.",
  "home.testimonial.explorer.title": "THE EXPLORER",
  "home.testimonial.explorer.subtitle": "Going deeper into Web3",

  "home.testimonial.builder.description":
    "Security is treated as part of the learning journey, not something that should only be considered after using Web3 applications.",
  "home.testimonial.builder.title": "THE BUILDER",
  "home.testimonial.builder.subtitle": "Learning to think technically",

  "home.faq.label": "[ FREQUENTLY ASKED QUESTIONS ]",
  "home.faq.title": "Got Questions?",
  "home.faq.titleSpan": "We've Got Answers.",

  "home.faq.free.question": "Is ChainLab free?",
  "home.faq.free.answer":
    "ChainLab is designed as a free educational resource for people who want to learn about blockchain and Web3 technologies.",
  "home.faq.experience.question":
    "Do I need previous blockchain experience?",
  "home.faq.experience.answer":
    "No. The learning path starts with foundational concepts and progressively introduces more specialized Web3 topics.",
  "home.faq.learn.question": "What can I learn on ChainLab?",
  "home.faq.learn.answer":
    "Current learning areas include blockchain, Solana, meme coins, and Web3 security, with additional topics planned as the learning system expands.",
  "home.faq.investment.question":
    "Is ChainLab an investment platform?",
  "home.faq.investment.answer":
    "No. ChainLab is an educational website. Its purpose is to provide learning material and help users understand Web3 concepts.",
  "home.faq.creator.question": "Who created ChainLab?",
  "home.faq.creator.answer":
    "ChainLab is an educational initiative created by Birthday Messaging.",

  "home.final.label": "[ READY TO START? ]",
  "home.final.title": "Your Web3",
  "home.final.titleSpan": "Learning Journey Starts Here.",
  "home.final.description":
    "Start with the fundamentals. Build your knowledge. Understand the technology.",

  "footer.description":
    "An educational platform created by Birthday Messaging to make blockchain and Web3 easier to understand.",
  "footer.tagline": "LEARN. PRACTICE. BUILD. SUCCEED.",
  "footer.learning": "LEARNING",
  "footer.learn": "Learn",
  "footer.blockchain": "Blockchain",
  "footer.solana": "Solana",
  "footer.memeCoins": "Meme Coins",
  "footer.security": "Security",
  "footer.chainlab": "CHAINLAB",
  "footer.learningPaths": "Learning Paths",
  "footer.about": "About",
  "footer.faq": "FAQ",
  "footer.company": "COMPANY",
  "footer.birthdayMessaging": "Birthday Messaging",
  "footer.educationalInitiative": "Educational Initiative",
  "footer.web3Education": "Web3 Education",
  "footer.copyright": "© 2026 Birthday Messaging. All rights reserved.",
  "footer.bottomTagline": "CHAINLAB — WEB3 EDUCATION",
};

const tn: TranslationDictionary = {
  "nav.blockchain": "BLOCKCHAIN",
  "nav.solana": "SOLANA",
  "nav.memeCoins": "DIDINWANE",
  "nav.security": "TSHIRELETSO",
  "home.hero.eyebrow": "[ THUTO YA WEB3 ]",
  "home.hero.learn": "ITHUTE",
  "home.hero.build": "AGA",
  "home.hero.ownThe": "TLHALOGANYA",
  "home.hero.future": "BOKAMOSO",
  "home.hero.description": "Ithute blockchain, Solana, meme coins, tokenomics le tshireletso ya Web3 ka dithuto tse di tlhaloganyegang sentle le tse di rulagantsweng.",
  "home.hero.startLearning": "SIMOLOLA GO ITHUTA",
  "home.hero.exploreTopics": "ITSE DITABA",
  "home.hero.note": "Ga go tlhokafale kitso ya blockchain pele.",
  "home.overview.kicker": "[ TLHOKOMELISO YA GO ITHUTA ]",
  "home.overview.title": "Aga Tlhaloganyo, Kgopolo e le Nngwe ka Nako.",
  "home.overview.intro": "Simolola ka metheo mme o kopanye megopolo e e dirang Web3.",
  "home.topics.kicker": "[ DITABA TSA MOTHEO ]",
  "home.topics.intro": "Ithute dithekenoloji, megopolo le dikotsi tse di bopang Web3.",
  "home.topic.blockchain.title": "BLOCKCHAIN",
  "home.topic.blockchain.description": "Tlhaloganya distributed ledgers, blocks, transactions, consensus le tsela e marangrang a blockchain a dirang ka yone.",
  "home.topic.blockchain.link": "ITHUTE BLOCKCHAIN",
  "home.topic.solana.title": "SOLANA",
  "home.topic.solana.description": "Ithute sebopego sa Solana, accounts, programs, transactions, validators le ecosystem ya yone.",
  "home.topic.solana.link": "ITHUTE SOLANA",
  "home.topic.memeCoins.title": "MEME COINS",
  "home.topic.memeCoins.description": "Tlhaloganya tokens, communities, liquidity, tokenomics, market dynamics le dikotsi.",
  "home.topic.memeCoins.link": "ITHUTE MEME COINS",
  "home.topic.security.title": "TSHIRELETSO",
  "home.topic.security.description": "Ithute ka wallets, private keys, scams, phishing, smart contracts le tiriso e e nang le maikarabelo ya Web3.",
  "home.topic.security.link": "ITHUTE TSHIRELETSO",
  "home.topic.dapps.title": "DAPPS",
  "home.topic.dapps.description": "Ithute gore decentralized applications di kopanya badirisi, smart contracts, wallets le blockchain jang.",
  "home.understand.title": "TLHALOGANYA",
  "home.understand.description": "Ithute gore blockchain ke eng, marangrang a a anameng a boloka tshedimosetso jang, le kamano ya blocks, transactions, consensus le validators.",
  "home.explore.title": "ITSE",
  "home.explore.description": "Latela kamano magareng ga wallets, keys, tokens, smart contracts, dApps le marangrang a a di tshegetsang.",
  "home.practise.title": "IKATISE",
  "home.practise.description": "Dirisa ditlhaloso tse di rulagantsweng le dikai go tiisa kitso ya gago le go aga motheo wa dithuto tse di latelang.",
  "home.bottom.startCurious": "SIMOLOLA O LE MOSIMANE.",
  "home.bottom.description": "Tswelela o ithuta ka lebelo la gago mme o age kitso kgato ka kgato.",
  "home.bottom.browse": "BULA LAEBORARI YA GO ITHUTA",
  "home.features.practical.title": "GO ITHUTA KA TIRISO",
  "home.features.practical.description": "Dithuto tsa kgato ka kgato tse di diretsweng ba simololang le ba ba batlang go aga Web3.",
  "home.features.web3.title": "E TEBILE MO WEB3",
  "home.features.web3.description": "Ithute blockchain, Solana, meme coins, tokenomics le dithekenoloji tse di sa laolweng ke setsi se le sengwe.",
  "home.features.security.title": "TSHIRELETSO",
  "home.features.security.description": "Tlhaloganya dikotsi tsa Web3 mme o ithute go itshireletsa mo lefatsheng le le anameng.",
  "home.features.community.title": "GO TSAYA KAROLO",
  "home.features.community.description": "Aga kitso e e ka go thusang go tsaya karolo mo Web3.",
  "home.stats.coreTopics": "DITABA TSA MOTHEO",
  "home.stats.learningPaths": "DIKGATO TSA GO ITHUTA",
  "home.stats.access": "GO FITLELELA",
  "home.about.label": "[ KA BIRTHDAY MESSAGING ]",
  "home.about.title": "Khamphani",
  "home.about.titleSpan": "E E Ka fa Morago ga ChainLab.",
  "home.about.description": "ChainLab ke porojeke ya thuto e e dirilweng ke Birthday Messaging go dira gore blockchain le Web3 di tlhaloganyesege bonolo.",
  "home.about.description2": "Fa dithekenoloji tse disha di fetola tsela e batho ba agang, ba buisanang le go dirang dilo ka yone mo inthaneteng, go tlhaloganya thekenoloji go nna botlhokwa.",
  "home.about.description3": "Birthday Messaging e dirile ChainLab e le lefelo la go ithuta moo batho ba ka simololang ka metheo mme ba fetela kwa ditlhogong tse di tseneletseng.",
  "home.about.button": "ITSE CHAINLAB",
  "home.about.companyLabel": "BIRTHDAY MESSAGING / CHAINLAB",
  "home.about.location": "THUTO / THEKENOLOJI / WEB3",
  "home.values.innovation.title": "BOITLHANG",
  "home.values.innovation.description": "Go batlisisa dithekenoloji tse disha le megopolo e e bopang bokamoso jwa dijithale.",
  "home.values.education.title": "THUTO",
  "home.values.education.description": "Go fetola megopolo e e raraaneng ya thekenoloji go nna kitso e e ka tlhaloganngwang.",
  "home.values.access.title": "GO FITLELELA",
  "home.values.access.description": "Go dira gore thuto ya motheo ya Web3 e fitlhelele batho kwantle ga dikgoreletsi tse di sa tlhokegeng.",
  "home.mission.label": "[ GOROGENG CHAINLAB ]",
  "home.about.whyTitle": "Web3 E A Fetoga.",
  "home.about.whyIntro": "Blockchain ga se cryptocurrency fela. E tlisa ditsela tse disha tsa go akanya ka ownership, digital assets, applications, identity le communities.",
  "home.mission.fundamentals.title": "SIMOLOLA KA METHEO",
  "home.mission.fundamentals.description": "Aga tlhaloganyo e e nonofileng ya blockchain pele o tsena mo dithekenolojing tse di tseneletseng.",
  "home.mission.connection.title": "ITHUTE KA KGOLAGANO",
  "home.mission.connection.description": "Tlhaloganya gore wallets, networks, transactions, tokens, applications le users di kopana jang.",
  "home.mission.risks.title": "TLHALOGANYA DIKOTSI",
  "home.mission.risks.description": "Ithute gore tshireletso, netefatso, patlisiso e e nang le maikarabelo le kelotlhoko di botlhokwa jang.",
  "home.mission.builder.title": "AKANYA JAALO KA MODIRI",
  "home.mission.builder.description": "Tsamaela kwa pele ga go dirisa thekenoloji fela mme o age kitso ya gore e dira jang.",
  "home.paths.label": "[ ITSE DIKGATO TSA GO ITHUTA ]",
  "home.paths.chooseTopic": "Tlhopha Setlhogo.",
  "home.paths.startJourney": "Simolola Loeto lwa Gago.",
  "home.paths.viewAll": "BONA DITHUTO TSOTLHE →",
  "home.paths.startModule": "SIMOLOLA THUTO →",
  "home.paths.comingSoon": "E TLA TLA",
  "home.paths.blockchain.title": "BLOCKCHAIN",
  "home.paths.blockchain.description": "Ithute metheo ya blockchain, decentralized networks, transactions, blocks le validation.",
  "home.paths.solana.title": "SOLANA",
  "home.paths.solana.description": "Ithute Solana, sebopego sa yone, accounts, programs, transactions le validators.",
  "home.paths.memeCoins.title": "MEME COINS",
  "home.paths.memeCoins.description": "Tlhaloganya tokens, communities, liquidity, tokenomics, market dynamics le dikotsi.",
  "home.paths.security.title": "TSHIRELETSO YA WEB3",
  "home.paths.security.description": "Ithute kamano ya wallets, private keys, scams, phishing, smart contracts le maikarabelo a modirisi.",
  "home.paths.tokenomics.title": "TOKENOMICS",
  "home.paths.tokenomics.description": "Ithute gore token supply, distribution, utility, incentives le market participation di ama digital assets jang.",
  "home.process.label": "[ CHAINLAB E DIRA JANG ]",
  "home.process.title": "Tsela e Bonolo ya",
  "home.process.titleSpan": "Kitso ya Web3.",
  "home.process.choose.title": "TLHOPHA",
  "home.process.choose.description": "Tlhopha setlhogo se se go kgatlhang mme o simolole ka metheo.",
  "home.process.follow.title": "LATELA",
  "home.process.follow.description": "Ithute ka ditlhaloso tse di rulagantsweng tse di dirang megopolo e e thata go tlhaloganngwa bonolo.",
  "home.process.connect.title": "KOPANYA",
  "home.process.connect.description": "Tlhaloganya gore dikarolo tse di farologaneng tsa Web3 di dira mmogo jang.",
  "home.process.keep.title": "TSWELELA GO ITHUTA",
  "home.process.keep.description": "Tswelela go aga kitso ya gago fa blockchain e ntse e gola.",
  "home.biggerPicture.label": "[ SETSHWANTSHO SE SE GODIMO ]",
  "home.biggerPicture.title1": "Bokamoso jo bo",
  "home.biggerPicture.title2": "Bulegileng,",
  "home.biggerPicture.title3": "Jo bo",
  "home.biggerPicture.title4": "Rutegileng jwa",
  "home.biggerPicture.title5": "Web3.",
  "home.biggerPicture.description": "Re dumela gore batho ba tshwanetse go tlhaloganya dithekenoloji tse ba dirisanang le tsone.",
  "home.biggerPicture.description2": "Le fa o le mosha mo blockchain, o ithuta Solana, o batlisisa meme coins kgotsa o ithuta go sireletsa digital assets, ChainLab e go naya lefelo la go aga motheo.",
  "home.biggerPicture.labelBottom": "THUTO YA CHAINLAB",
  "home.biggerPicture.location": "LEFATSHE / ONLINE",
  "home.security.label": "[ TSHIRELETSO PELE ]",
  "home.security.title": "Kitso Ke Karolo",
  "home.security.titleSpan": "ya Tshireletso ya Gago.",
  "home.security.description": "Web3 e naya badirisi taolo e kgolwane, mme taolo e kgolwane e tla le maikarabelo a kgolwane.",
  "home.security.description2": "Go tlhaloganya wallets, private keys, transactions, phishing, contracts tse di kotsi, scams le social engineering go ka thusa badirisi go dira ditshwetso tse di botoka.",
  "home.security.button": "ITHUTE TSHIRELETSO →",
  "home.security.imageLabel": "NETEFATSA PELE O SAENA",
  "home.learning.label": "[ MAITEMOGELO A GO ITHUTA ]",
  "home.learning.title": "E DIRETSWE BA BA RATANG GO ITSE",
  "home.learning.titleSpan": "BA ITHUTI.",
  "home.testimonial.beginner.title": "YO O SIMOLOLANG",
  "home.testimonial.beginner.subtitle": "Go simolola loeto lwa Web3",
  "home.testimonial.beginner.description": "ChainLab e tlhalosa megopolo ka botlalo go na le go tsaya gore moithuti o setse a itse thekenoloji.",
  "home.testimonial.explorer.title": "MOTLHOTLHOMI",
  "home.testimonial.explorer.subtitle": "Go tsena boteng mo Web3",
  "home.testimonial.explorer.description": "Mokgwa o o rulagantsweng o dira gore go nne bonolo go kopanya metheo ya blockchain le Solana le token ecosystems.",
  "home.testimonial.builder.title": "MODIRI",
  "home.testimonial.builder.subtitle": "Go ithuta go akanya ka thekeniki",
  "home.testimonial.builder.description": "Tshireletso e tsewa e le karolo ya loeto lwa go ithuta, e seng sengwe se se akanyediwang morago.",
  "home.faq.label": "[ DIPOTSO TSE DI BODIWANG GANTSI ]",
  "home.faq.title": "O Na le Dipotso?",
  "home.faq.titleSpan": "Re Na le Dikarabo.",
  "home.faq.free.question": "A ChainLab ke mahala?",
  "home.faq.free.answer": "ChainLab e diretswe go nna motswedi wa thuto ya mahala ya batho ba ba batlang go ithuta blockchain le Web3.",
  "home.faq.experience.question": "A ke tlhoka maitemogelo a blockchain?",
  "home.faq.experience.answer": "Nnyaa. Loeto lwa go ithuta lo simolola ka metheo mme lo tswelela kwa ditlhogong tse di tseneletseng.",
  "home.faq.learn.question": "Nka ithuta eng mo ChainLab?",
  "home.faq.learn.answer": "Dikarolo tsa ga jaana di akaretsa blockchain, Solana, meme coins le tshireletso ya Web3.",
  "home.faq.investment.question": "A ChainLab ke platform ya dipeeletso?",
  "home.faq.investment.answer": "Nnyaa. ChainLab ke webosaete ya thuto e e dirilweng go thusa batho go tlhaloganya megopolo ya Web3.",
  "home.faq.creator.question": "Ke mang yo o dirileng ChainLab?",
  "home.faq.creator.answer": "ChainLab ke porojeke ya thuto e e dirilweng ke Birthday Messaging.",
  "home.final.label": "[ A RE SIMOLOLE? ]",
  "home.final.title": "Loeto lwa Gago lwa Web3",
  "home.final.titleSpan": "Lo Simolola Fano.",
  "home.final.description": "Simolola ka metheo. Aga kitso ya gago. Tlhaloganya thekenoloji.",
  "footer.description": "Platform ya thuto e e dirilweng ke Birthday Messaging go dira blockchain le Web3 bonolo go tlhaloganngwa.",
  "footer.tagline": "ITHUTE. IKATISE. AGA. ATLEGA.",
  "footer.learning": "GO ITHUTA",
  "footer.learn": "Ithute",
  "footer.blockchain": "Blockchain",
  "footer.solana": "Solana",
  "footer.memeCoins": "Meme Coins",
  "footer.security": "Tshireletso",
  "footer.chainlab": "CHAINLAB",
  "footer.learningPaths": "Dikgato tsa go Ithuta",
  "footer.about": "Ka Rona",
  "footer.faq": "Dipotso",
  "footer.company": "KHAMPHANI",
  "footer.birthdayMessaging": "Birthday Messaging",
  "footer.educationalInitiative": "Porojeke ya Thuto",
  "footer.web3Education": "Thuto ya Web3",
  "footer.copyright": "© 2026 Birthday Messaging. Ditshwanelo tsotlhe di sireleditswe.",
  "footer.bottomTagline": "CHAINLAB — THUTO YA WEB3"
};

const fr: TranslationDictionary = {
  "nav.blockchain": "BLOCKCHAIN",
  "nav.solana": "SOLANA",
  "nav.memeCoins": "MEME COINS",
  "nav.security": "SÉCURITÉ",
  "home.hero.eyebrow": "[ ÉDUCATION WEB3 ]",
  "home.hero.learn": "APPRENDRE",
  "home.hero.build": "CONSTRUIRE",
  "home.hero.ownThe": "COMPRENDRE LE",
  "home.hero.future": "FUTUR",
  "home.hero.description": "Apprenez la blockchain, Solana, les meme coins, la tokenomics et la sécurité Web3 avec des leçons claires et structurées.",
  "home.hero.startLearning": "COMMENCER À APPRENDRE",
  "home.hero.exploreTopics": "EXPLORER LES SUJETS",
  "home.hero.note": "Aucune expérience préalable en blockchain requise.",
  "home.overview.kicker": "[ APERÇU DE L'APPRENTISSAGE ]",
  "home.overview.title": "Construisez votre compréhension, un concept à la fois.",
  "home.overview.intro": "Commencez par les fondamentaux et reliez progressivement les idées qui font fonctionner le Web3.",
  "home.topics.kicker": "[ SUJETS PRINCIPAUX ]",
  "home.topics.intro": "Explorez les technologies, concepts et risques qui façonnent l'écosystème Web3.",
  "home.topic.blockchain.title": "BLOCKCHAIN",
  "home.topic.blockchain.description": "Comprenez les registres distribués, les blocs, les transactions, le consensus et le fonctionnement des réseaux blockchain.",
  "home.topic.blockchain.link": "APPRENDRE LA BLOCKCHAIN",
  "home.topic.solana.title": "SOLANA",
  "home.topic.solana.description": "Découvrez l'architecture de Solana, les comptes, programmes, transactions, validateurs et son écosystème.",
  "home.topic.solana.link": "APPRENDRE SOLANA",
  "home.topic.memeCoins.title": "MEME COINS",
  "home.topic.memeCoins.description": "Comprenez les tokens, communautés, liquidité, tokenomics, dynamiques de marché et risques.",
  "home.topic.memeCoins.link": "APPRENDRE LES MEME COINS",
  "home.topic.security.title": "SÉCURITÉ",
  "home.topic.security.description": "Découvrez les portefeuilles, clés privées, arnaques, phishing, contrats intelligents et l'usage responsable du Web3.",
  "home.topic.security.link": "APPRENDRE LA SÉCURITÉ",
  "home.topic.dapps.title": "DAPPS",
  "home.topic.dapps.description": "Découvrez comment les applications décentralisées relient utilisateurs, contrats intelligents, portefeuilles et réseaux blockchain.",
  "home.understand.title": "COMPRENDRE",
  "home.understand.description": "Découvrez ce qu'est une blockchain et comment blocs, transactions, consensus et validateurs sont liés.",
  "home.explore.title": "EXPLORER",
  "home.explore.description": "Suivez les liens entre portefeuilles, clés, tokens, contrats intelligents, applications décentralisées et réseaux.",
  "home.practise.title": "PRATIQUER",
  "home.practise.description": "Utilisez des explications structurées et des exemples pratiques pour renforcer votre compréhension.",
  "home.bottom.startCurious": "COMMENCEZ PAR CURIOSITÉ.",
  "home.bottom.description": "Continuez à apprendre à votre rythme et construisez votre compréhension étape par étape.",
  "home.bottom.browse": "PARCOURIR LA BIBLIOTHÈQUE",
  "home.features.practical.title": "APPRENTISSAGE PRATIQUE",
  "home.features.practical.description": "Des leçons étape par étape conçues pour les débutants et futurs créateurs Web3.",
  "home.features.web3.title": "CENTRÉ SUR LE WEB3",
  "home.features.web3.description": "Apprenez la blockchain, Solana, les meme coins, la tokenomics et les technologies décentralisées.",
  "home.features.security.title": "SENSIBILISATION À LA SÉCURITÉ",
  "home.features.security.description": "Comprenez les risques du Web3 et apprenez à vous protéger.",
  "home.features.community.title": "PRÊT POUR LA COMMUNAUTÉ",
  "home.features.community.description": "Développez des connaissances pour participer à l'écosystème Web3.",
  "home.stats.coreTopics": "SUJETS PRINCIPAUX",
  "home.stats.learningPaths": "PARCOURS",
  "home.stats.access": "ACCÈS",
  "home.about.label": "[ À PROPOS DE BIRTHDAY MESSAGING ]",
  "home.about.title": "L'entreprise",
  "home.about.titleSpan": "Derrière ChainLab.",
  "home.about.description": "ChainLab est une initiative éducative créée par Birthday Messaging pour rendre la blockchain et le Web3 plus faciles à comprendre.",
  "home.about.description2": "Alors que les technologies émergentes changent la façon dont nous construisons, communiquons et participons en ligne, comprendre leur technologie devient de plus en plus important.",
  "home.about.description3": "Birthday Messaging a créé ChainLab comme environnement d'apprentissage où chacun peut progresser des fondamentaux vers des sujets Web3 plus avancés.",
  "home.about.button": "EXPLORER CHAINLAB",
  "home.about.companyLabel": "BIRTHDAY MESSAGING / CHAINLAB",
  "home.about.location": "ÉDUCATION / TECHNOLOGIE / WEB3",
  "home.mission.label": "[ POURQUOI CHAINLAB ]",
  "home.about.whyTitle": "Le Web3 évolue.",
  "home.about.whyIntro": "La blockchain est plus que la cryptomonnaie. Elle propose de nouvelles façons de penser la propriété, les actifs numériques, les applications et les communautés.",
  "home.mission.fundamentals.title": "COMMENCER PAR LES FONDAMENTAUX",
  "home.mission.fundamentals.description": "Construisez une solide compréhension de la blockchain avant les technologies spécialisées.",
  "home.mission.connection.title": "APPRENDRE PAR CONNEXION",
  "home.mission.connection.description": "Comprenez comment portefeuilles, réseaux, transactions, tokens, applications et utilisateurs s'assemblent.",
  "home.mission.risks.title": "COMPRENDRE LES RISQUES",
  "home.mission.risks.description": "Apprenez pourquoi sécurité, vérification, recherche responsable et vigilance sont importantes.",
  "home.mission.builder.title": "PENSER COMME UN CRÉATEUR",
  "home.mission.builder.description": "Allez au-delà de l'utilisation de la technologie et comprenez comment elle fonctionne.",
  "home.paths.label": "[ EXPLOREZ NOS PARCOURS ]",
  "home.paths.chooseTopic": "Choisissez un sujet.",
  "home.paths.startJourney": "Commencez votre parcours.",
  "home.paths.viewAll": "VOIR TOUS LES MODULES →",
  "home.paths.startModule": "COMMENCER LE MODULE →",
  "home.paths.comingSoon": "BIENTÔT",
  "home.paths.blockchain.title": "BLOCKCHAIN",
  "home.paths.blockchain.description": "Apprenez les fondamentaux de la blockchain, des réseaux distribués, transactions, blocs et validation.",
  "home.paths.solana.title": "SOLANA",
  "home.paths.solana.description": "Explorez Solana, son architecture, ses comptes, programmes, transactions et validateurs.",
  "home.paths.memeCoins.title": "MEME COINS",
  "home.paths.memeCoins.description": "Comprenez tokens, communautés, liquidité, tokenomics, marchés et risques.",
  "home.paths.security.title": "SÉCURITÉ WEB3",
  "home.paths.security.description": "Découvrez les liens entre portefeuilles, clés privées, arnaques, phishing, contrats intelligents et responsabilité.",
  "home.paths.tokenomics.title": "TOKENOMICS",
  "home.paths.tokenomics.description": "Découvrez comment offre, distribution, utilité et incitations influencent les actifs numériques.",
  "home.process.label": "[ COMMENT CHAINLAB FONCTIONNE ]",
  "home.process.title": "Un chemin simple vers",
  "home.process.titleSpan": "la connaissance Web3.",
  "home.process.choose.title": "CHOISIR",
  "home.process.choose.description": "Choisissez un sujet qui vous intéresse et commencez par les fondamentaux.",
  "home.process.follow.title": "SUIVRE",
  "home.process.follow.description": "Apprenez avec des explications structurées conçues pour rendre les concepts difficiles plus simples.",
  "home.process.connect.title": "CONNECTER",
  "home.process.connect.description": "Comprenez comment les différentes parties du Web3 fonctionnent ensemble.",
  "home.process.keep.title": "CONTINUER",
  "home.process.keep.description": "Développez vos connaissances à mesure que la blockchain évolue.",
  "home.security.label": "[ SÉCURITÉ D'ABORD ]",
  "home.security.title": "La connaissance fait partie",
  "home.security.titleSpan": "de votre sécurité.",
  "home.security.description": "Le Web3 donne plus de contrôle aux utilisateurs, mais aussi plus de responsabilité.",
  "home.security.description2": "Comprendre portefeuilles, clés privées, transactions, phishing, contrats malveillants et arnaques aide à prendre de meilleures décisions.",
  "home.security.button": "APPRENDRE LA SÉCURITÉ →",
  "home.security.imageLabel": "VÉRIFIEZ AVANT DE SIGNER",
  "home.faq.label": "[ QUESTIONS FRÉQUENTES ]",
  "home.faq.title": "Des questions ?",
  "home.faq.titleSpan": "Nous avons les réponses.",
  "home.faq.free.question": "ChainLab est-il gratuit ?",
  "home.faq.free.answer": "ChainLab est conçu comme une ressource éducative gratuite sur la blockchain et le Web3.",
  "home.faq.experience.question": "Faut-il une expérience préalable ?",
  "home.faq.experience.answer": "Non. Le parcours commence par les fondamentaux puis introduit progressivement des sujets plus spécialisés.",
  "home.faq.learn.question": "Que puis-je apprendre sur ChainLab ?",
  "home.faq.learn.answer": "Les domaines actuels comprennent blockchain, Solana, meme coins et sécurité Web3.",
  "home.faq.investment.question": "ChainLab est-il une plateforme d'investissement ?",
  "home.faq.investment.answer": "Non. ChainLab est un site éducatif destiné à aider les utilisateurs à comprendre le Web3.",
  "home.faq.creator.question": "Qui a créé ChainLab ?",
  "home.faq.creator.answer": "ChainLab est une initiative éducative créée par Birthday Messaging.",
  "home.final.label": "[ PRÊT À COMMENCER ? ]",
  "home.final.title": "Votre parcours Web3",
  "home.final.titleSpan": "commence ici.",
  "home.final.description": "Commencez par les fondamentaux. Construisez vos connaissances. Comprenez la technologie.",
  "footer.description": "Une plateforme éducative créée par Birthday Messaging pour rendre la blockchain et le Web3 plus faciles à comprendre.",
  "footer.tagline": "APPRENDRE. PRATIQUER. CONSTRUIRE. RÉUSSIR.",
  "footer.learning": "APPRENTISSAGE",
  "footer.learn": "Apprendre",
  "footer.blockchain": "Blockchain",
  "footer.solana": "Solana",
  "footer.memeCoins": "Meme Coins",
  "footer.security": "Sécurité",
  "footer.chainlab": "CHAINLAB",
  "footer.learningPaths": "Parcours",
  "footer.about": "À propos",
  "footer.faq": "FAQ",
  "footer.company": "ENTREPRISE",
  "footer.birthdayMessaging": "Birthday Messaging",
  "footer.educationalInitiative": "Initiative éducative",
  "footer.web3Education": "Éducation Web3",
  "footer.copyright": "© 2026 Birthday Messaging. Tous droits réservés.",
  "footer.bottomTagline": "CHAINLAB — ÉDUCATION WEB3"
};

const es: TranslationDictionary = {
  "nav.blockchain": "BLOCKCHAIN",
  "nav.solana": "SOLANA",
  "nav.memeCoins": "MEME COINS",
  "nav.security": "SEGURIDAD",
  "home.hero.eyebrow": "[ EDUCACIÓN WEB3 ]",
  "home.hero.learn": "APRENDE",
  "home.hero.build": "CONSTRUYE",
  "home.hero.ownThe": "ENTIENDE EL",
  "home.hero.future": "FUTURO",
  "home.hero.description": "Aprende blockchain, Solana, meme coins, tokenomics y seguridad Web3 mediante lecciones claras y estructuradas.",
  "home.hero.startLearning": "EMPEZAR A APRENDER",
  "home.hero.exploreTopics": "EXPLORAR TEMAS",
  "home.hero.note": "No necesitas experiencia previa en blockchain.",
  "home.overview.kicker": "[ RESUMEN DE APRENDIZAJE ]",
  "home.overview.title": "Construye comprensión, un concepto a la vez.",
  "home.overview.intro": "Empieza con los fundamentos y conecta progresivamente las ideas que hacen funcionar Web3.",
  "home.topics.kicker": "[ TEMAS PRINCIPALES ]",
  "home.topics.intro": "Explora las tecnologías, conceptos y riesgos que forman el ecosistema Web3.",
  "home.topic.blockchain.title": "BLOCKCHAIN",
  "home.topic.blockchain.description": "Comprende registros distribuidos, bloques, transacciones, consenso y cómo funcionan las redes blockchain.",
  "home.topic.blockchain.link": "APRENDER BLOCKCHAIN",
  "home.topic.solana.title": "SOLANA",
  "home.topic.solana.description": "Explora la arquitectura de Solana, cuentas, programas, transacciones, validadores y su ecosistema.",
  "home.topic.solana.link": "APRENDER SOLANA",
  "home.topic.memeCoins.title": "MEME COINS",
  "home.topic.memeCoins.description": "Comprende tokens, comunidades, liquidez, tokenomics, dinámica del mercado y riesgos.",
  "home.topic.memeCoins.link": "APRENDER MEME COINS",
  "home.topic.security.title": "SEGURIDAD",
  "home.topic.security.description": "Aprende sobre billeteras, claves privadas, estafas, phishing, contratos inteligentes y uso responsable de Web3.",
  "home.topic.security.link": "APRENDER SEGURIDAD",
  "home.topic.dapps.title": "DAPPS",
  "home.topic.dapps.description": "Descubre cómo las aplicaciones descentralizadas conectan usuarios, contratos inteligentes, billeteras y redes blockchain.",
  "home.understand.title": "ENTENDER",
  "home.understand.description": "Descubre qué es una blockchain y cómo se relacionan bloques, transacciones, consenso y validadores.",
  "home.explore.title": "EXPLORAR",
  "home.explore.description": "Sigue las conexiones entre billeteras, claves, tokens, contratos inteligentes, dApps y redes.",
  "home.practise.title": "PRACTICAR",
  "home.practise.description": "Usa explicaciones estructuradas y ejemplos prácticos para reforzar cada tema y construir una base sólida.",
  "home.bottom.startCurious": "EMPIEZA CON CURIOSIDAD.",
  "home.bottom.description": "Sigue aprendiendo a tu ritmo y construye tu comprensión paso a paso.",
  "home.bottom.browse": "EXPLORAR LA BIBLIOTECA",
  "home.features.practical.title": "APRENDIZAJE PRÁCTICO",
  "home.features.practical.description": "Lecciones paso a paso diseñadas para principiantes y futuros creadores de Web3.",
  "home.features.web3.title": "ENFOCADO EN WEB3",
  "home.features.web3.description": "Aprende blockchain, Solana, meme coins, tokenomics y tecnologías descentralizadas.",
  "home.features.security.title": "SEGURIDAD",
  "home.features.security.description": "Comprende los riesgos de Web3 y aprende a protegerte.",
  "home.features.community.title": "LISTO PARA LA COMUNIDAD",
  "home.features.community.description": "Construye conocimientos para participar en el ecosistema Web3.",
  "home.stats.coreTopics": "TEMAS PRINCIPALES",
  "home.stats.learningPaths": "RUTAS DE APRENDIZAJE",
  "home.stats.access": "ACCESO",
  "home.about.label": "[ SOBRE BIRTHDAY MESSAGING ]",
  "home.about.title": "La empresa",
  "home.about.titleSpan": "detrás de ChainLab.",
  "home.about.description": "ChainLab es una iniciativa educativa creada por Birthday Messaging para hacer que blockchain y Web3 sean más fáciles de entender.",
  "home.about.description2": "A medida que las tecnologías emergentes cambian cómo las personas construyen, comunican y participan en línea, comprender la tecnología se vuelve cada vez más importante.",
  "home.about.description3": "Birthday Messaging creó ChainLab como un entorno de aprendizaje donde las personas pueden avanzar desde los fundamentos hacia temas Web3 más avanzados.",
  "home.about.button": "EXPLORAR CHAINLAB",
  "home.about.companyLabel": "BIRTHDAY MESSAGING / CHAINLAB",
  "home.about.location": "EDUCACIÓN / TECNOLOGÍA / WEB3",
  "home.mission.label": "[ POR QUÉ CHAINLAB ]",
  "home.about.whyTitle": "Web3 está cambiando.",
  "home.about.whyIntro": "Blockchain es más que criptomonedas. Introduce nuevas formas de pensar sobre propiedad, activos digitales, aplicaciones y comunidades.",
  "home.mission.fundamentals.title": "EMPIEZA POR LOS FUNDAMENTOS",
  "home.mission.fundamentals.description": "Construye una comprensión sólida de blockchain antes de pasar a tecnologías especializadas.",
  "home.mission.connection.title": "APRENDE POR CONEXIÓN",
  "home.mission.connection.description": "Comprende cómo encajan billeteras, redes, transacciones, tokens, aplicaciones y usuarios.",
  "home.mission.risks.title": "ENTIENDE LOS RIESGOS",
  "home.mission.risks.description": "Aprende por qué la seguridad, verificación, investigación responsable y atención son importantes.",
  "home.mission.builder.title": "PIENSA COMO UN CREADOR",
  "home.mission.builder.description": "Ve más allá de usar tecnología y desarrolla conocimientos para entender cómo funciona.",
  "home.paths.label": "[ EXPLORA NUESTRAS RUTAS ]",
  "home.paths.chooseTopic": "Elige un tema.",
  "home.paths.startJourney": "Comienza tu recorrido.",
  "home.paths.viewAll": "VER TODOS LOS MÓDULOS →",
  "home.paths.startModule": "EMPEZAR MÓDULO →",
  "home.paths.comingSoon": "PRÓXIMAMENTE",
  "home.paths.blockchain.title": "BLOCKCHAIN",
  "home.paths.blockchain.description": "Aprende los fundamentos de blockchain, redes descentralizadas, transacciones, bloques y validación.",
  "home.paths.solana.title": "SOLANA",
  "home.paths.solana.description": "Explora Solana, su arquitectura, cuentas, programas, transacciones y validadores.",
  "home.paths.memeCoins.title": "MEME COINS",
  "home.paths.memeCoins.description": "Comprende tokens, comunidades, liquidez, tokenomics, mercados y riesgos.",
  "home.paths.security.title": "SEGURIDAD WEB3",
  "home.paths.security.description": "Aprende cómo se conectan billeteras, claves privadas, estafas, phishing, contratos inteligentes y responsabilidad.",
  "home.paths.tokenomics.title": "TOKENOMICS",
  "home.paths.tokenomics.description": "Descubre cómo oferta, distribución, utilidad e incentivos influyen en los activos digitales.",
  "home.process.label": "[ CÓMO FUNCIONA CHAINLAB ]",
  "home.process.title": "Un camino sencillo hacia",
  "home.process.titleSpan": "el conocimiento Web3.",
  "home.process.choose.title": "ELEGIR",
  "home.process.choose.description": "Elige un tema que te interese y empieza por los fundamentos.",
  "home.process.follow.title": "SEGUIR",
  "home.process.follow.description": "Aprende con explicaciones estructuradas diseñadas para hacer más fáciles los conceptos difíciles.",
  "home.process.connect.title": "CONECTAR",
  "home.process.connect.description": "Comprende cómo funcionan juntas las diferentes partes de Web3.",
  "home.process.keep.title": "SEGUIR APRENDIENDO",
  "home.process.keep.description": "Continúa desarrollando tus conocimientos mientras evoluciona blockchain.",
  "home.security.label": "[ SEGURIDAD PRIMERO ]",
  "home.security.title": "El conocimiento forma parte",
  "home.security.titleSpan": "de tu seguridad.",
  "home.security.description": "Web3 ofrece más control a los usuarios, pero también más responsabilidad.",
  "home.security.description2": "Comprender billeteras, claves privadas, transacciones, phishing, contratos maliciosos y estafas puede ayudar a tomar mejores decisiones.",
  "home.security.button": "APRENDER SEGURIDAD →",
  "home.security.imageLabel": "VERIFICA ANTES DE FIRMAR",
  "home.faq.label": "[ PREGUNTAS FRECUENTES ]",
  "home.faq.title": "¿Tienes preguntas?",
  "home.faq.titleSpan": "Tenemos respuestas.",
  "home.faq.free.question": "¿ChainLab es gratis?",
  "home.faq.free.answer": "ChainLab está diseñado como un recurso educativo gratuito para aprender sobre blockchain y Web3.",
  "home.faq.experience.question": "¿Necesito experiencia previa?",
  "home.faq.experience.answer": "No. La ruta comienza con conceptos fundamentales y avanza hacia temas Web3 más especializados.",
  "home.faq.learn.question": "¿Qué puedo aprender en ChainLab?",
  "home.faq.learn.answer": "Las áreas actuales incluyen blockchain, Solana, meme coins y seguridad Web3.",
  "home.faq.investment.question": "¿ChainLab es una plataforma de inversión?",
  "home.faq.investment.answer": "No. ChainLab es un sitio educativo para ayudar a comprender conceptos de Web3.",
  "home.faq.creator.question": "¿Quién creó ChainLab?",
  "home.faq.creator.answer": "ChainLab es una iniciativa educativa creada por Birthday Messaging.",
  "home.final.label": "[ ¿LISTO PARA EMPEZAR? ]",
  "home.final.title": "Tu viaje Web3",
  "home.final.titleSpan": "empieza aquí.",
  "home.final.description": "Empieza por los fundamentos. Construye tus conocimientos. Comprende la tecnología.",
  "footer.description": "Una plataforma educativa creada por Birthday Messaging para hacer blockchain y Web3 más fáciles de entender.",
  "footer.tagline": "APRENDER. PRACTICAR. CONSTRUIR. TRIUNFAR.",
  "footer.learning": "APRENDIZAJE",
  "footer.learn": "Aprender",
  "footer.blockchain": "Blockchain",
  "footer.solana": "Solana",
  "footer.memeCoins": "Meme Coins",
  "footer.security": "Seguridad",
  "footer.chainlab": "CHAINLAB",
  "footer.learningPaths": "Rutas de aprendizaje",
  "footer.about": "Acerca de",
  "footer.faq": "FAQ",
  "footer.company": "EMPRESA",
  "footer.birthdayMessaging": "Birthday Messaging",
  "footer.educationalInitiative": "Iniciativa educativa",
  "footer.web3Education": "Educación Web3",
  "footer.copyright": "© 2026 Birthday Messaging. Todos los derechos reservados.",
  "footer.bottomTagline": "CHAINLAB — EDUCACIÓN WEB3"
};

const pt: TranslationDictionary = {
  "nav.blockchain": "BLOCKCHAIN",
  "nav.solana": "SOLANA",
  "nav.memeCoins": "MEME COINS",
  "nav.security": "SEGURANÇA",
  "home.hero.eyebrow": "[ EDUCAÇÃO WEB3 ]",
  "home.hero.learn": "APRENDA",
  "home.hero.build": "CONSTRUA",
  "home.hero.ownThe": "ENTENDA O",
  "home.hero.future": "FUTURO",
  "home.hero.description": "Aprenda blockchain, Solana, meme coins, tokenomics e segurança Web3 com lições claras e estruturadas.",
  "home.hero.startLearning": "COMEÇAR A APRENDER",
  "home.hero.exploreTopics": "EXPLORAR TÓPICOS",
  "home.hero.note": "Não é necessária experiência prévia em blockchain.",
  "home.overview.kicker": "[ VISÃO GERAL ]",
  "home.overview.title": "Construa entendimento, um conceito de cada vez.",
  "home.overview.intro": "Comece pelos fundamentos e conecte progressivamente as ideias que fazem o Web3 funcionar.",
  "home.topics.kicker": "[ TÓPICOS PRINCIPAIS ]",
  "home.topics.intro": "Explore tecnologias, conceitos e riscos que moldam o ecossistema Web3.",
  "home.topic.blockchain.title": "BLOCKCHAIN",
  "home.topic.blockchain.description": "Entenda registros distribuídos, blocos, transações, consenso e como funcionam as redes blockchain.",
  "home.topic.blockchain.link": "APRENDER BLOCKCHAIN",
  "home.topic.solana.title": "SOLANA",
  "home.topic.solana.description": "Explore a arquitetura da Solana, contas, programas, transações, validadores e seu ecossistema.",
  "home.topic.solana.link": "APRENDER SOLANA",
  "home.topic.memeCoins.title": "MEME COINS",
  "home.topic.memeCoins.description": "Entenda tokens, comunidades, liquidez, tokenomics, dinâmica de mercado e riscos.",
  "home.topic.memeCoins.link": "APRENDER MEME COINS",
  "home.topic.security.title": "SEGURANÇA",
  "home.topic.security.description": "Aprenda sobre carteiras, chaves privadas, golpes, phishing, contratos inteligentes e uso responsável do Web3.",
  "home.topic.security.link": "APRENDER SEGURANÇA",
  "home.topic.dapps.title": "DAPPS",
  "home.topic.dapps.description": "Descubra como aplicações descentralizadas conectam usuários, contratos, carteiras e redes blockchain.",
  "home.understand.title": "ENTENDER",
  "home.understand.description": "Descubra o que é uma blockchain e como blocos, transações, consenso e validadores se relacionam.",
  "home.explore.title": "EXPLORAR",
  "home.explore.description": "Acompanhe as conexões entre carteiras, chaves, tokens, contratos inteligentes, dApps e redes.",
  "home.practise.title": "PRATICAR",
  "home.practise.description": "Use explicações estruturadas e exemplos práticos para reforçar cada tema.",
  "home.features.practical.title": "APRENDIZAGEM PRÁTICA",
  "home.features.web3.title": "FOCADO EM WEB3",
  "home.features.security.title": "SEGURANÇA",
  "home.features.community.title": "PRONTO PARA A COMUNIDADE",
  "home.about.label": "[ SOBRE A BIRTHDAY MESSAGING ]",
  "home.about.title": "A empresa",
  "home.about.titleSpan": "por trás da ChainLab.",
  "home.about.description": "A ChainLab é uma iniciativa educacional criada pela Birthday Messaging para tornar blockchain e Web3 mais fáceis de entender.",
  "home.about.button": "EXPLORAR CHAINLAB",
  "home.about.location": "EDUCAÇÃO / TECNOLOGIA / WEB3",
  "home.mission.label": "[ POR QUE CHAINLAB ]",
  "home.about.whyTitle": "O Web3 está mudando.",
  "home.about.whyIntro": "Blockchain é mais do que criptomoeda. Ela traz novas formas de pensar sobre propriedade, ativos digitais, aplicações e comunidades.",
  "home.mission.fundamentals.title": "COMECE PELOS FUNDAMENTOS",
  "home.mission.connection.title": "APRENDA POR CONEXÃO",
  "home.mission.risks.title": "ENTENDA OS RISCOS",
  "home.mission.builder.title": "PENSE COMO UM CRIADOR",
  "home.paths.label": "[ EXPLORE NOSSOS CAMINHOS ]",
  "home.paths.chooseTopic": "Escolha um tópico.",
  "home.paths.startJourney": "Comece sua jornada.",
  "home.paths.viewAll": "VER TODOS OS MÓDULOS →",
  "home.paths.startModule": "COMEÇAR MÓDULO →",
  "home.paths.comingSoon": "EM BREVE",
  "home.paths.blockchain.title": "BLOCKCHAIN",
  "home.paths.solana.title": "SOLANA",
  "home.paths.memeCoins.title": "MEME COINS",
  "home.paths.security.title": "SEGURANÇA WEB3",
  "home.paths.tokenomics.title": "TOKENOMICS",
  "home.process.label": "[ COMO A CHAINLAB FUNCIONA ]",
  "home.process.title": "Um caminho simples para",
  "home.process.titleSpan": "o conhecimento Web3.",
  "home.process.choose.title": "ESCOLHER",
  "home.process.follow.title": "SEGUIR",
  "home.process.connect.title": "CONECTAR",
  "home.process.keep.title": "CONTINUAR APRENDENDO",
  "home.security.label": "[ SEGURANÇA PRIMEIRO ]",
  "home.security.title": "Conhecimento faz parte",
  "home.security.titleSpan": "da sua segurança.",
  "home.security.button": "APRENDER SEGURANÇA →",
  "home.security.imageLabel": "VERIFIQUE ANTES DE ASSINAR",
  "home.learning.label": "[ EXPERIÊNCIA DE APRENDIZAGEM ]",
  "home.learning.title": "Feito para pessoas curiosas",
  "home.learning.titleSpan": "e aprendizes.",
  "home.faq.label": "[ PERGUNTAS FREQUENTES ]",
  "home.faq.title": "Tem perguntas?",
  "home.faq.titleSpan": "Temos respostas.",
  "home.faq.free.question": "A ChainLab é gratuita?",
  "home.faq.experience.question": "Preciso de experiência prévia?",
  "home.faq.learn.question": "O que posso aprender na ChainLab?",
  "home.faq.investment.question": "A ChainLab é uma plataforma de investimento?",
  "home.faq.creator.question": "Quem criou a ChainLab?",
  "home.final.label": "[ PRONTO PARA COMEÇAR? ]",
  "home.final.title": "Sua jornada Web3",
  "home.final.titleSpan": "começa aqui.",
  "home.final.description": "Comece pelos fundamentos. Construa seu conhecimento. Entenda a tecnologia.",
  "footer.description": "Uma plataforma educacional criada pela Birthday Messaging para tornar blockchain e Web3 mais fáceis de entender.",
  "footer.tagline": "APRENDER. PRATICAR. CONSTRUIR. VENCER.",
  "footer.learning": "APRENDIZAGEM",
  "footer.learn": "Aprender",
  "footer.security": "Segurança",
  "footer.learningPaths": "Caminhos de aprendizagem",
  "footer.about": "Sobre",
  "footer.company": "EMPRESA"
};

const de: TranslationDictionary = {
  "nav.blockchain": "BLOCKCHAIN",
  "nav.solana": "SOLANA",
  "nav.memeCoins": "MEME COINS",
  "nav.security": "SICHERHEIT",
  "home.hero.eyebrow": "[ WEB3-BILDUNG ]",
  "home.hero.learn": "LERNEN",
  "home.hero.build": "BAUEN",
  "home.hero.ownThe": "VERSTEHE DIE",
  "home.hero.future": "ZUKUNFT",
  "home.hero.description": "Lerne Blockchain, Solana, Meme Coins, Tokenomics und Web3-Sicherheit mit klaren, strukturierten Lektionen.",
  "home.hero.startLearning": "JETZT LERNEN",
  "home.hero.exploreTopics": "THEMEN ENTDECKEN",
  "home.hero.note": "Keine Vorkenntnisse in Blockchain erforderlich.",
  "home.overview.kicker": "[ LERNÜBERSICHT ]",
  "home.overview.title": "Verständnis aufbauen, Konzept für Konzept.",
  "home.overview.intro": "Beginne mit den Grundlagen und verbinde Schritt für Schritt die Ideen hinter Web3.",
  "home.topics.kicker": "[ KERNTHEMEN ]",
  "home.topics.intro": "Entdecke Technologien, Konzepte und Risiken des Web3-Ökosystems.",
  "home.topic.blockchain.title": "BLOCKCHAIN",
  "home.topic.blockchain.description": "Verstehe verteilte Register, Blöcke, Transaktionen, Konsens und Blockchain-Netzwerke.",
  "home.topic.blockchain.link": "BLOCKCHAIN LERNEN",
  "home.topic.solana.title": "SOLANA",
  "home.topic.solana.description": "Entdecke Solanas Architektur, Konten, Programme, Transaktionen, Validatoren und Ökosystem.",
  "home.topic.solana.link": "SOLANA LERNEN",
  "home.topic.memeCoins.title": "MEME COINS",
  "home.topic.memeCoins.description": "Verstehe Tokens, Communities, Liquidität, Tokenomics, Marktdynamik und Risiken.",
  "home.topic.memeCoins.link": "MEME COINS LERNEN",
  "home.topic.security.title": "SICHERHEIT",
  "home.topic.security.description": "Lerne über Wallets, private Schlüssel, Betrug, Phishing, Smart Contracts und sicheren Web3-Einsatz.",
  "home.topic.security.link": "SICHERHEIT LERNEN",
  "home.topic.dapps.title": "DAPPS",
  "home.topic.dapps.description": "Entdecke, wie dezentrale Anwendungen Nutzer, Smart Contracts, Wallets und Blockchain-Netzwerke verbinden.",
  "home.understand.title": "VERSTEHEN",
  "home.understand.description": "Entdecke, was eine Blockchain ist und wie Blöcke, Transaktionen, Konsens und Validatoren zusammenhängen.",
  "home.explore.title": "ENTDECKEN",
  "home.explore.description": "Verfolge die Verbindungen zwischen Wallets, Schlüsseln, Tokens, Smart Contracts und Netzwerken.",
  "home.practise.title": "ÜBEN",
  "home.practise.description": "Nutze strukturierte Erklärungen und praktische Beispiele, um dein Verständnis zu festigen.",
  "home.features.practical.title": "PRAKTISCHES LERNEN",
  "home.features.web3.title": "WEB3-FOKUS",
  "home.features.security.title": "SICHERHEITSBEWUSST",
  "home.features.community.title": "COMMUNITY-BEREIT",
  "home.about.label": "[ ÜBER BIRTHDAY MESSAGING ]",
  "home.about.title": "Das Unternehmen",
  "home.about.titleSpan": "hinter ChainLab.",
  "home.about.description": "ChainLab ist eine Bildungsinitiative von Birthday Messaging, die Blockchain und Web3 verständlicher machen soll.",
  "home.about.button": "CHAINLAB ENTDECKEN",
  "home.about.location": "BILDUNG / TECHNOLOGIE / WEB3",
  "home.mission.label": "[ WARUM CHAINLAB ]",
  "home.about.whyTitle": "Web3 verändert sich.",
  "home.about.whyIntro": "Blockchain ist mehr als Kryptowährung. Sie eröffnet neue Denkweisen über Eigentum, digitale Assets, Anwendungen und Communities.",
  "home.mission.fundamentals.title": "MIT DEN GRUNDLAGEN BEGINNEN",
  "home.mission.connection.title": "DURCH VERBINDUNGEN LERNEN",
  "home.mission.risks.title": "RISIKEN VERSTEHEN",
  "home.mission.builder.title": "WIE EIN BUILDER DENKEN",
  "home.paths.label": "[ UNSERE LERNPFADE ]",
  "home.paths.chooseTopic": "Wähle ein Thema.",
  "home.paths.startJourney": "Starte deine Reise.",
  "home.paths.viewAll": "ALLE MODULE ANSEHEN →",
  "home.paths.startModule": "MODUL STARTEN →",
  "home.paths.comingSoon": "BALD VERFÜGBAR",
  "home.paths.blockchain.title": "BLOCKCHAIN",
  "home.paths.solana.title": "SOLANA",
  "home.paths.memeCoins.title": "MEME COINS",
  "home.paths.security.title": "WEB3-SICHERHEIT",
  "home.paths.tokenomics.title": "TOKENOMICS",
  "home.process.label": "[ SO FUNKTIONIERT CHAINLAB ]",
  "home.process.title": "Ein einfacher Weg zu",
  "home.process.titleSpan": "Web3-Wissen.",
  "home.process.choose.title": "WÄHLEN",
  "home.process.follow.title": "FOLGEN",
  "home.process.connect.title": "VERBINDEN",
  "home.process.keep.title": "WEITERLERNEN",
  "home.security.label": "[ SICHERHEIT ZUERST ]",
  "home.security.title": "Wissen ist Teil",
  "home.security.titleSpan": "deiner Sicherheit.",
  "home.security.button": "SICHERHEIT LERNEN →",
  "home.security.imageLabel": "VOR DEM SIGNIEREN PRÜFEN",
  "home.faq.label": "[ HÄUFIGE FRAGEN ]",
  "home.faq.title": "Fragen?",
  "home.faq.titleSpan": "Wir haben Antworten.",
  "home.faq.free.question": "Ist ChainLab kostenlos?",
  "home.faq.experience.question": "Brauche ich Vorkenntnisse?",
  "home.faq.learn.question": "Was kann ich auf ChainLab lernen?",
  "home.faq.investment.question": "Ist ChainLab eine Investmentplattform?",
  "home.faq.creator.question": "Wer hat ChainLab erstellt?",
  "home.final.label": "[ BEREIT ZU STARTEN? ]",
  "home.final.title": "Deine Web3-Reise",
  "home.final.titleSpan": "beginnt hier.",
  "home.final.description": "Beginne mit den Grundlagen. Baue dein Wissen auf. Verstehe die Technologie.",
  "footer.description": "Eine Bildungsplattform von Birthday Messaging, die Blockchain und Web3 verständlicher macht.",
  "footer.tagline": "LERNEN. ÜBEN. BAUEN. ERFOLGREICH SEIN.",
  "footer.learning": "LERNEN",
  "footer.learn": "Lernen",
  "footer.security": "Sicherheit",
  "footer.learningPaths": "Lernpfade",
  "footer.about": "Über uns",
  "footer.company": "UNTERNEHMEN"
};

const zh: TranslationDictionary = {
  "nav.blockchain": "区块链",
  "nav.solana": "SOLANA",
  "nav.memeCoins": "Meme 币",
  "nav.security": "安全",
  "home.hero.eyebrow": "[ WEB3 教育 ]",
  "home.hero.learn": "学习",
  "home.hero.build": "构建",
  "home.hero.ownThe": "理解",
  "home.hero.future": "未来",
  "home.hero.description": "通过清晰、结构化的课程学习区块链、Solana、Meme 币、代币经济学和 Web3 安全。",
  "home.hero.startLearning": "开始学习",
  "home.hero.exploreTopics": "探索主题",
  "home.hero.note": "无需区块链基础经验。",
  "home.overview.kicker": "[ 学习概览 ]",
  "home.overview.title": "一次掌握一个概念，逐步建立理解。",
  "home.overview.intro": "从基础开始，逐步连接构成 Web3 的重要概念。",
  "home.topics.kicker": "[ 核心主题 ]",
  "home.topics.intro": "探索塑造 Web3 生态的技术、概念与风险。",
  "home.topic.blockchain.title": "区块链",
  "home.topic.blockchain.description": "了解分布式账本、区块、交易、共识以及区块链网络的运行方式。",
  "home.topic.blockchain.link": "学习区块链",
  "home.topic.solana.title": "SOLANA",
  "home.topic.solana.description": "探索 Solana 架构、账户、程序、交易、验证者及其生态。",
  "home.topic.solana.link": "学习 SOLANA",
  "home.topic.memeCoins.title": "MEME 币",
  "home.topic.memeCoins.description": "了解代币、社区、流动性、代币经济学、市场动态与风险。",
  "home.topic.memeCoins.link": "学习 MEME 币",
  "home.topic.security.title": "安全",
  "home.topic.security.description": "学习钱包、私钥、诈骗、钓鱼、智能合约以及负责任的 Web3 使用方式。",
  "home.topic.security.link": "学习安全",
  "home.topic.dapps.title": "DAPP",
  "home.topic.dapps.description": "了解去中心化应用如何连接用户、智能合约、钱包和区块链网络。",
  "home.understand.title": "理解",
  "home.understand.description": "了解区块链是什么，以及区块、交易、共识和验证者之间的关系。",
  "home.explore.title": "探索",
  "home.explore.description": "了解钱包、密钥、代币、智能合约、DApp 与网络之间的联系。",
  "home.practise.title": "实践",
  "home.practise.description": "通过结构化解释和实际例子巩固每个主题。",
  "home.features.practical.title": "实践学习",
  "home.features.web3.title": "专注 WEB3",
  "home.features.security.title": "安全意识",
  "home.features.community.title": "社区参与",
  "home.about.label": "[ 关于 BIRTHDAY MESSAGING ]",
  "home.about.title": "背后的公司",
  "home.about.titleSpan": "ChainLab 背后的团队。",
  "home.about.description": "ChainLab 是 Birthday Messaging 创建的教育项目，旨在让区块链和 Web3 更容易理解。",
  "home.about.button": "探索 CHAINLAB",
  "home.about.location": "教育 / 技术 / WEB3",
  "home.mission.label": "[ 为什么选择 CHAINLAB ]",
  "home.about.whyTitle": "Web3 正在改变。",
  "home.about.whyIntro": "区块链不只是加密货币，它带来了关于所有权、数字资产、应用和社区的新思考方式。",
  "home.mission.fundamentals.title": "从基础开始",
  "home.mission.connection.title": "通过连接学习",
  "home.mission.risks.title": "理解风险",
  "home.mission.builder.title": "像构建者一样思考",
  "home.paths.label": "[ 探索学习路径 ]",
  "home.paths.chooseTopic": "选择一个主题。",
  "home.paths.startJourney": "开始你的旅程。",
  "home.paths.viewAll": "查看所有模块 →",
  "home.paths.startModule": "开始模块 →",
  "home.paths.comingSoon": "即将推出",
  "home.paths.blockchain.title": "区块链",
  "home.paths.solana.title": "SOLANA",
  "home.paths.memeCoins.title": "MEME 币",
  "home.paths.security.title": "WEB3 安全",
  "home.paths.tokenomics.title": "代币经济学",
  "home.process.label": "[ CHAINLAB 如何运作 ]",
  "home.process.title": "通往",
  "home.process.titleSpan": "Web3 知识的简单路径。",
  "home.process.choose.title": "选择",
  "home.process.follow.title": "跟随",
  "home.process.connect.title": "连接",
  "home.process.keep.title": "持续学习",
  "home.security.label": "[ 安全第一 ]",
  "home.security.title": "知识是",
  "home.security.titleSpan": "安全的一部分。",
  "home.security.button": "学习安全 →",
  "home.security.imageLabel": "签名前先验证",
  "home.faq.label": "[ 常见问题 ]",
  "home.faq.title": "有问题？",
  "home.faq.titleSpan": "我们有答案。",
  "home.faq.free.question": "ChainLab 免费吗？",
  "home.faq.experience.question": "需要区块链经验吗？",
  "home.faq.learn.question": "可以在 ChainLab 学什么？",
  "home.faq.investment.question": "ChainLab 是投资平台吗？",
  "home.faq.creator.question": "谁创建了 ChainLab？",
  "home.final.label": "[ 准备开始了吗？ ]",
  "home.final.title": "你的 Web3",
  "home.final.titleSpan": "学习旅程从这里开始。",
  "home.final.description": "从基础开始。建立知识。理解技术。",
  "footer.description": "由 Birthday Messaging 创建的教育平台，让区块链和 Web3 更容易理解。",
  "footer.tagline": "学习。实践。构建。成长。",
  "footer.learning": "学习",
  "footer.learn": "开始学习",
  "footer.security": "安全",
  "footer.learningPaths": "学习路径",
  "footer.about": "关于",
  "footer.company": "公司"
};

const ar: TranslationDictionary = {
  "nav.blockchain": "البلوك تشين",
  "nav.solana": "سولانا",
  "nav.memeCoins": "عملات الميم",
  "nav.security": "الأمان",
  "home.hero.eyebrow": "[ تعليم WEB3 ]",
  "home.hero.learn": "تعلّم",
  "home.hero.build": "ابنِ",
  "home.hero.ownThe": "افهم",
  "home.hero.future": "المستقبل",
  "home.hero.description": "تعلّم البلوك تشين وسولانا وعملات الميم واقتصاديات الرموز وأمان Web3 من خلال دروس واضحة ومنظمة.",
  "home.hero.startLearning": "ابدأ التعلّم",
  "home.hero.exploreTopics": "استكشف المواضيع",
  "home.hero.note": "لا تحتاج إلى خبرة سابقة في البلوك تشين.",
  "home.overview.kicker": "[ نظرة على التعلّم ]",
  "home.overview.title": "ابنِ فهمك، مفهوماً بعد مفهوم.",
  "home.overview.intro": "ابدأ بالأساسيات واربط تدريجياً الأفكار التي تجعل Web3 يعمل.",
  "home.topics.kicker": "[ المواضيع الأساسية ]",
  "home.topics.intro": "استكشف التقنيات والمفاهيم والمخاطر التي تشكل منظومة Web3.",
  "home.topic.blockchain.title": "البلوك تشين",
  "home.topic.blockchain.description": "افهم السجلات الموزعة والكتل والمعاملات وآليات الإجماع وكيف تعمل شبكات البلوك تشين.",
  "home.topic.blockchain.link": "تعلّم البلوك تشين",
  "home.topic.solana.title": "سولانا",
  "home.topic.solana.description": "استكشف بنية سولانا والحسابات والبرامج والمعاملات والمدققين ومنظومتها.",
  "home.topic.solana.link": "تعلّم سولانا",
  "home.topic.memeCoins.title": "عملات الميم",
  "home.topic.memeCoins.description": "افهم الرموز والمجتمعات والسيولة واقتصاديات الرموز وديناميكيات السوق والمخاطر.",
  "home.topic.memeCoins.link": "تعلّم عملات الميم",
  "home.topic.security.title": "الأمان",
  "home.topic.security.description": "تعلّم عن المحافظ والمفاتيح الخاصة والاحتيال والتصيد والعقود الذكية والاستخدام المسؤول لـ Web3.",
  "home.topic.security.link": "تعلّم الأمان",
  "home.topic.dapps.title": "التطبيقات اللامركزية",
  "home.topic.dapps.description": "اكتشف كيف تربط التطبيقات اللامركزية المستخدمين والعقود الذكية والمحافظ وشبكات البلوك تشين.",
  "home.understand.title": "افهم",
  "home.understand.description": "اكتشف ما هو البلوك تشين وكيف ترتبط الكتل والمعاملات والإجماع والمدققون.",
  "home.explore.title": "استكشف",
  "home.explore.description": "تعرّف على الروابط بين المحافظ والمفاتيح والرموز والعقود الذكية والتطبيقات والشبكات.",
  "home.practise.title": "تدرّب",
  "home.practise.description": "استخدم الشروحات المنظمة والأمثلة العملية لترسيخ فهمك.",
  "home.features.practical.title": "تعلّم عملي",
  "home.features.web3.title": "متخصص في WEB3",
  "home.features.security.title": "وعي أمني",
  "home.features.community.title": "جاهز للمجتمع",
  "home.about.label": "[ عن BIRTHDAY MESSAGING ]",
  "home.about.title": "الشركة",
  "home.about.titleSpan": "خلف ChainLab.",
  "home.about.description": "ChainLab مبادرة تعليمية أنشأتها Birthday Messaging لتسهيل فهم البلوك تشين وWeb3.",
  "home.about.button": "استكشف CHAINLAB",
  "home.about.location": "التعليم / التقنية / WEB3",
  "home.mission.label": "[ لماذا CHAINLAB ]",
  "home.about.whyTitle": "Web3 يتغير.",
  "home.about.whyIntro": "البلوك تشين أكثر من مجرد عملات مشفرة؛ فهو يقدم طرقاً جديدة للتفكير في الملكية والأصول الرقمية والتطبيقات والمجتمعات.",
  "home.mission.fundamentals.title": "ابدأ بالأساسيات",
  "home.mission.connection.title": "تعلّم من خلال الترابط",
  "home.mission.risks.title": "افهم المخاطر",
  "home.mission.builder.title": "فكّر كصانع",
  "home.paths.label": "[ استكشف مسارات التعلّم ]",
  "home.paths.chooseTopic": "اختر موضوعاً.",
  "home.paths.startJourney": "ابدأ رحلتك.",
  "home.paths.viewAll": "عرض جميع الوحدات →",
  "home.paths.startModule": "ابدأ الوحدة →",
  "home.paths.comingSoon": "قريباً",
  "home.paths.blockchain.title": "البلوك تشين",
  "home.paths.solana.title": "سولانا",
  "home.paths.memeCoins.title": "عملات الميم",
  "home.paths.security.title": "أمان WEB3",
  "home.paths.tokenomics.title": "اقتصاديات الرموز",
  "home.process.label": "[ كيف تعمل CHAINLAB ]",
  "home.process.title": "طريق بسيط إلى",
  "home.process.titleSpan": "معرفة Web3.",
  "home.process.choose.title": "اختر",
  "home.process.follow.title": "اتبع",
  "home.process.connect.title": "اربط",
  "home.process.keep.title": "واصل التعلّم",
  "home.security.label": "[ الأمان أولاً ]",
  "home.security.title": "المعرفة جزء من",
  "home.security.titleSpan": "أمانك.",
  "home.security.button": "تعلّم الأمان →",
  "home.security.imageLabel": "تحقق قبل التوقيع",
  "home.faq.label": "[ الأسئلة الشائعة ]",
  "home.faq.title": "لديك أسئلة؟",
  "home.faq.titleSpan": "لدينا إجابات.",
  "home.faq.free.question": "هل ChainLab مجانية؟",
  "home.faq.experience.question": "هل أحتاج خبرة سابقة؟",
  "home.faq.learn.question": "ماذا يمكنني أن أتعلم في ChainLab؟",
  "home.faq.investment.question": "هل ChainLab منصة استثمار؟",
  "home.faq.creator.question": "من أنشأ ChainLab؟",
  "home.final.label": "[ مستعد للبدء؟ ]",
  "home.final.title": "رحلتك في Web3",
  "home.final.titleSpan": "تبدأ من هنا.",
  "home.final.description": "ابدأ بالأساسيات. ابنِ معرفتك. افهم التقنية.",
  "footer.description": "منصة تعليمية أنشأتها Birthday Messaging لتسهيل فهم البلوك تشين وWeb3.",
  "footer.tagline": "تعلّم. تدرّب. ابنِ. تقدّم.",
  "footer.learning": "التعلّم",
  "footer.learn": "تعلّم",
  "footer.security": "الأمان",
  "footer.learningPaths": "مسارات التعلّم",
  "footer.about": "حول",
  "footer.company": "الشركة"
};

const hi: TranslationDictionary = {
  "nav.blockchain": "ब्लॉकचेन",
  "nav.solana": "सोलाना",
  "nav.memeCoins": "मीम कॉइन्स",
  "nav.security": "सुरक्षा",
  "home.hero.eyebrow": "[ WEB3 शिक्षा ]",
  "home.hero.learn": "सीखें",
  "home.hero.build": "बनाएँ",
  "home.hero.ownThe": "समझें",
  "home.hero.future": "भविष्य",
  "home.hero.description": "स्पष्ट और व्यवस्थित पाठों के माध्यम से ब्लॉकचेन, सोलाना, मीम कॉइन्स, टोकनोमिक्स और Web3 सुरक्षा सीखें।",
  "home.hero.startLearning": "सीखना शुरू करें",
  "home.hero.exploreTopics": "विषय देखें",
  "home.hero.note": "ब्लॉकचेन का पूर्व अनुभव आवश्यक नहीं है।",
  "home.overview.kicker": "[ सीखने का अवलोकन ]",
  "home.overview.title": "एक समय में एक अवधारणा समझें।",
  "home.overview.intro": "मूल बातों से शुरू करें और Web3 को चलाने वाले विचारों को धीरे-धीरे जोड़ें।",
  "home.topics.kicker": "[ मुख्य विषय ]",
  "home.topics.intro": "Web3 को आकार देने वाली तकनीकों, अवधारणाओं और जोखिमों को जानें।",
  "home.topic.blockchain.title": "ब्लॉकचेन",
  "home.topic.blockchain.description": "डिस्ट्रिब्यूटेड लेजर, ब्लॉक, लेनदेन, कंसेंसस और ब्लॉकचेन नेटवर्क की कार्यप्रणाली समझें।",
  "home.topic.blockchain.link": "ब्लॉकचेन सीखें",
  "home.topic.solana.title": "सोलाना",
  "home.topic.solana.description": "सोलाना की आर्किटेक्चर, अकाउंट्स, प्रोग्राम्स, ट्रांजैक्शन और वैलिडेटर्स को जानें।",
  "home.topic.solana.link": "सोलाना सीखें",
  "home.topic.memeCoins.title": "मीम कॉइन्स",
  "home.topic.memeCoins.description": "टोकन, समुदाय, लिक्विडिटी, टोकनोमिक्स, बाजार और जोखिम समझें।",
  "home.topic.memeCoins.link": "मीम कॉइन्स सीखें",
  "home.topic.security.title": "सुरक्षा",
  "home.topic.security.description": "वॉलेट, प्राइवेट की, स्कैम, फिशिंग, स्मार्ट कॉन्ट्रैक्ट और सुरक्षित Web3 उपयोग सीखें।",
  "home.topic.security.link": "सुरक्षा सीखें",
  "home.topic.dapps.title": "DAPPS",
  "home.topic.dapps.description": "जानें कि विकेंद्रीकृत ऐप्स उपयोगकर्ताओं, स्मार्ट कॉन्ट्रैक्ट्स, वॉलेट और ब्लॉकचेन नेटवर्क को कैसे जोड़ते हैं।",
  "home.understand.title": "समझें",
  "home.understand.description": "जानें कि ब्लॉकचेन क्या है और ब्लॉक, ट्रांजैक्शन, कंसेंसस और वैलिडेटर कैसे जुड़े हैं।",
  "home.explore.title": "खोजें",
  "home.explore.description": "वॉलेट, की, टोकन, स्मार्ट कॉन्ट्रैक्ट, dApps और नेटवर्क के बीच संबंध समझें।",
  "home.practise.title": "अभ्यास करें",
  "home.practise.description": "संरचित व्याख्याओं और उदाहरणों से अपनी समझ मजबूत करें।",
  "home.features.practical.title": "व्यावहारिक सीख",
  "home.features.web3.title": "WEB3 केंद्रित",
  "home.features.security.title": "सुरक्षा जागरूक",
  "home.features.community.title": "समुदाय के लिए तैयार",
  "home.about.label": "[ BIRTHDAY MESSAGING के बारे में ]",
  "home.about.title": "कंपनी",
  "home.about.titleSpan": "ChainLab के पीछे।",
  "home.about.description": "ChainLab Birthday Messaging द्वारा बनाया गया एक शैक्षिक पहल है जो ब्लॉकचेन और Web3 को समझना आसान बनाती है।",
  "home.about.button": "CHAINLAB देखें",
  "home.about.location": "शिक्षा / तकनीक / WEB3",
  "home.mission.label": "[ CHAINLAB क्यों ]",
  "home.about.whyTitle": "Web3 बदल रहा है।",
  "home.about.whyIntro": "ब्लॉकचेन केवल क्रिप्टोकरेंसी नहीं है। यह स्वामित्व, डिजिटल संपत्ति, ऐप्स और समुदायों के बारे में नए तरीके से सोचने का अवसर देता है।",
  "home.mission.fundamentals.title": "मूल बातों से शुरू करें",
  "home.mission.connection.title": "संबंधों से सीखें",
  "home.mission.risks.title": "जोखिम समझें",
  "home.mission.builder.title": "बिल्डर की तरह सोचें",
  "home.paths.label": "[ सीखने के रास्ते ]",
  "home.paths.chooseTopic": "एक विषय चुनें।",
  "home.paths.startJourney": "अपनी यात्रा शुरू करें।",
  "home.paths.viewAll": "सभी मॉड्यूल देखें →",
  "home.paths.startModule": "मॉड्यूल शुरू करें →",
  "home.paths.comingSoon": "जल्द आ रहा है",
  "home.paths.blockchain.title": "ब्लॉकचेन",
  "home.paths.solana.title": "सोलाना",
  "home.paths.memeCoins.title": "मीम कॉइन्स",
  "home.paths.security.title": "WEB3 सुरक्षा",
  "home.paths.tokenomics.title": "टोकनोमिक्स",
  "home.process.label": "[ CHAINLAB कैसे काम करता है ]",
  "home.process.title": "एक सरल रास्ता",
  "home.process.titleSpan": "Web3 ज्ञान तक।",
  "home.process.choose.title": "चुनें",
  "home.process.follow.title": "अनुसरण करें",
  "home.process.connect.title": "जोड़ें",
  "home.process.keep.title": "सीखते रहें",
  "home.security.label": "[ सुरक्षा पहले ]",
  "home.security.title": "ज्ञान आपकी",
  "home.security.titleSpan": "सुरक्षा का हिस्सा है।",
  "home.security.button": "सुरक्षा सीखें →",
  "home.security.imageLabel": "साइन करने से पहले सत्यापित करें",
  "home.faq.label": "[ अक्सर पूछे जाने वाले प्रश्न ]",
  "home.faq.title": "सवाल हैं?",
  "home.faq.titleSpan": "हमारे पास जवाब हैं।",
  "home.faq.free.question": "क्या ChainLab मुफ्त है?",
  "home.faq.experience.question": "क्या मुझे पहले से अनुभव चाहिए?",
  "home.faq.learn.question": "मैं ChainLab पर क्या सीख सकता हूँ?",
  "home.faq.investment.question": "क्या ChainLab निवेश प्लेटफ़ॉर्म है?",
  "home.faq.creator.question": "ChainLab किसने बनाया?",
  "home.final.label": "[ शुरू करने के लिए तैयार? ]",
  "home.final.title": "आपकी Web3",
  "home.final.titleSpan": "सीखने की यात्रा यहाँ से शुरू होती है।",
  "home.final.description": "मूल बातों से शुरू करें। अपना ज्ञान बनाएँ। तकनीक को समझें।",
  "footer.description": "Birthday Messaging द्वारा बनाया गया शैक्षिक प्लेटफ़ॉर्म जो ब्लॉकचेन और Web3 को समझना आसान बनाता है।",
  "footer.tagline": "सीखें। अभ्यास करें। बनाएँ। आगे बढ़ें।",
  "footer.learning": "सीखना",
  "footer.learn": "सीखें",
  "footer.security": "सुरक्षा",
  "footer.learningPaths": "सीखने के रास्ते",
  "footer.about": "हमारे बारे में",
  "footer.company": "कंपनी"
};

const sw: TranslationDictionary = {
  "nav.blockchain": "BLOCKCHAIN",
  "nav.solana": "SOLANA",
  "nav.memeCoins": "MEME COINS",
  "nav.security": "USALAMA",
  "home.hero.eyebrow": "[ ELIMU YA WEB3 ]",
  "home.hero.learn": "JIFUNZE",
  "home.hero.build": "JENGA",
  "home.hero.ownThe": "ELEWA",
  "home.hero.future": "BAADAYE",
  "home.hero.description": "Jifunze blockchain, Solana, meme coins, tokenomics na usalama wa Web3 kupitia masomo yaliyo wazi na yaliyopangwa.",
  "home.hero.startLearning": "ANZA KUJIFUNZA",
  "home.hero.exploreTopics": "CHUNGUZA MADA",
  "home.hero.note": "Huhitaji uzoefu wa awali wa blockchain.",
  "home.overview.kicker": "[ MUHTASARI WA KUJIFUNZA ]",
  "home.overview.title": "Jenga uelewa, dhana moja kwa wakati.",
  "home.overview.intro": "Anza na misingi na uunganishe hatua kwa hatua mawazo yanayofanya Web3 ifanye kazi.",
  "home.topics.kicker": "[ MADA KUU ]",
  "home.topics.intro": "Chunguza teknolojia, dhana na hatari zinazounda mfumo wa Web3.",
  "home.topic.blockchain.title": "BLOCKCHAIN",
  "home.topic.blockchain.description": "Elewa ledger zilizosambazwa, blocks, transactions, consensus na jinsi mitandao ya blockchain inavyofanya kazi.",
  "home.topic.blockchain.link": "JIFUNZE BLOCKCHAIN",
  "home.topic.solana.title": "SOLANA",
  "home.topic.solana.description": "Chunguza usanifu wa Solana, accounts, programs, transactions, validators na mfumo wake.",
  "home.topic.solana.link": "JIFUNZE SOLANA",
  "home.topic.memeCoins.title": "MEME COINS",
  "home.topic.memeCoins.description": "Elewa tokens, communities, liquidity, tokenomics, mienendo ya soko na hatari.",
  "home.topic.memeCoins.link": "JIFUNZE MEME COINS",
  "home.topic.security.title": "USALAMA",
  "home.topic.security.description": "Jifunze kuhusu wallets, private keys, scams, phishing, smart contracts na matumizi salama ya Web3.",
  "home.topic.security.link": "JIFUNZE USALAMA",
  "home.topic.dapps.title": "DAPPS",
  "home.topic.dapps.description": "Gundua jinsi programu zilizogatuliwa zinavyounganisha watumiaji, smart contracts, wallets na mitandao.",
  "home.understand.title": "ELEWA",
  "home.understand.description": "Gundua blockchain ni nini na jinsi blocks, transactions, consensus na validators zinavyohusiana.",
  "home.explore.title": "CHUNGUZA",
  "home.explore.description": "Fuata uhusiano kati ya wallets, keys, tokens, smart contracts, dApps na mitandao.",
  "home.practise.title": "FANYA MAZOEZI",
  "home.practise.description": "Tumia maelezo yaliyopangwa na mifano ya vitendo kuimarisha uelewa wako.",
  "home.features.practical.title": "KUJIFUNZA KWA VITENDO",
  "home.features.web3.title": "INALENGA WEB3",
  "home.features.security.title": "UFahamu WA USALAMA",
  "home.features.community.title": "TAYARI KWA JAMII",
  "home.about.label": "[ KUHUSU BIRTHDAY MESSAGING ]",
  "home.about.title": "Kampuni",
  "home.about.titleSpan": "iliyo nyuma ya ChainLab.",
  "home.about.description": "ChainLab ni mpango wa elimu ulioundwa na Birthday Messaging ili kufanya blockchain na Web3 iwe rahisi kuelewa.",
  "home.about.button": "CHUNGUZA CHAINLAB",
  "home.about.location": "ELIMU / TEKNOLOJIA / WEB3",
  "home.mission.label": "[ KWA NINI CHAINLAB ]",
  "home.about.whyTitle": "Web3 inabadilika.",
  "home.about.whyIntro": "Blockchain ni zaidi ya cryptocurrency. Inaleta njia mpya za kufikiria kuhusu umiliki, mali za kidijitali, programu na jamii.",
  "home.mission.fundamentals.title": "ANZA NA MSINGI",
  "home.mission.connection.title": "JIFUNZE KWA KUUNGANISHA",
  "home.mission.risks.title": "ELEWA HATARI",
  "home.mission.builder.title": "FIKIRI KAMA MTAALAMU",
  "home.paths.label": "[ CHUNGUZA NJIA ZETU ZA KUJIFUNZA ]",
  "home.paths.chooseTopic": "Chagua mada.",
  "home.paths.startJourney": "Anza safari yako.",
  "home.paths.viewAll": "TAZAMA MODULI ZOTE →",
  "home.paths.startModule": "ANZA MODULI →",
  "home.paths.comingSoon": "INAKUJA HIVI KARIBUNI",
  "home.paths.blockchain.title": "BLOCKCHAIN",
  "home.paths.solana.title": "SOLANA",
  "home.paths.memeCoins.title": "MEME COINS",
  "home.paths.security.title": "USALAMA WA WEB3",
  "home.paths.tokenomics.title": "TOKENOMICS",
  "home.process.label": "[ JINSI CHAINLAB INAVYOFANYA KAZI ]",
  "home.process.title": "Njia rahisi ya kuelekea",
  "home.process.titleSpan": "maarifa ya Web3.",
  "home.process.choose.title": "CHAGUA",
  "home.process.follow.title": "FUATA",
  "home.process.connect.title": "UNGANISHA",
  "home.process.keep.title": "ENDELEA KUJIFUNZA",
  "home.security.label": "[ USALAMA KWANZA ]",
  "home.security.title": "Maarifa ni sehemu ya",
  "home.security.titleSpan": "usalama wako.",
  "home.security.button": "JIFUNZE USALAMA →",
  "home.security.imageLabel": "HAKIKI KABLA YA KUSAINI",
  "home.faq.label": "[ MASWALI YANAYOULIZWA MARA KWA MARA ]",
  "home.faq.title": "Una maswali?",
  "home.faq.titleSpan": "Tuna majibu.",
  "home.faq.free.question": "Je, ChainLab ni bure?",
  "home.faq.experience.question": "Je, nahitaji uzoefu wa awali?",
  "home.faq.learn.question": "Naweza kujifunza nini kwenye ChainLab?",
  "home.faq.investment.question": "Je, ChainLab ni jukwaa la uwekezaji?",
  "home.faq.creator.question": "Nani alianzisha ChainLab?",
  "home.final.label": "[ UKO TAYARI KUANZA? ]",
  "home.final.title": "Safari yako ya Web3",
  "home.final.titleSpan": "inaanzia hapa.",
  "home.final.description": "Anza na misingi. Jenga maarifa yako. Elewa teknolojia.",
  "footer.description": "Jukwaa la elimu lililoundwa na Birthday Messaging ili kufanya blockchain na Web3 iwe rahisi kuelewa.",
  "footer.tagline": "JIFUNZE. FANYA MAZOEZI. JENGA. FANIKIWA.",
  "footer.learning": "KUJIFUNZA",
  "footer.learn": "Jifunze",
  "footer.security": "Usalama",
  "footer.learningPaths": "Njia za kujifunza",
  "footer.about": "Kuhusu",
  "footer.company": "KAMPUNI"
};

const ja: TranslationDictionary = {
  "nav.blockchain": "ブロックチェーン",
  "nav.solana": "SOLANA",
  "nav.memeCoins": "ミームコイン",
  "nav.security": "セキュリティ",
  "home.hero.eyebrow": "[ WEB3 教育 ]",
  "home.hero.learn": "学ぶ",
  "home.hero.build": "つくる",
  "home.hero.ownThe": "理解する",
  "home.hero.future": "未来",
  "home.hero.description": "明確で体系的なレッスンを通して、ブロックチェーン、Solana、ミームコイン、トークノミクス、Web3セキュリティを学びます。",
  "home.hero.startLearning": "学習を始める",
  "home.hero.exploreTopics": "テーマを見る",
  "home.hero.note": "ブロックチェーンの経験は必要ありません。",
  "home.overview.kicker": "[ 学習概要 ]",
  "home.overview.title": "一つずつ概念を理解しよう。",
  "home.overview.intro": "基礎から始め、Web3を支える考え方を段階的につなげます。",
  "home.topics.kicker": "[ コアテーマ ]",
  "home.topics.intro": "Web3を形づくる技術、概念、リスクを学びます。",
  "home.topic.blockchain.title": "ブロックチェーン",
  "home.topic.blockchain.description": "分散型台帳、ブロック、トランザクション、コンセンサス、ネットワークの仕組みを理解します。",
  "home.topic.blockchain.link": "ブロックチェーンを学ぶ",
  "home.topic.solana.title": "SOLANA",
  "home.topic.solana.description": "Solanaのアーキテクチャ、アカウント、プログラム、トランザクション、バリデータを学びます。",
  "home.topic.solana.link": "SOLANAを学ぶ",
  "home.topic.memeCoins.title": "ミームコイン",
  "home.topic.memeCoins.description": "トークン、コミュニティ、流動性、トークノミクス、市場の動きとリスクを理解します。",
  "home.topic.memeCoins.link": "ミームコインを学ぶ",
  "home.topic.security.title": "セキュリティ",
  "home.topic.security.description": "ウォレット、秘密鍵、詐欺、フィッシング、スマートコントラクト、安全なWeb3利用を学びます。",
  "home.topic.security.link": "セキュリティを学ぶ",
  "home.topic.dapps.title": "DApps",
  "home.topic.dapps.description": "分散型アプリがユーザー、スマートコントラクト、ウォレット、ブロックチェーンをどうつなぐかを学びます。",
  "home.understand.title": "理解",
  "home.understand.description": "ブロックチェーンとは何か、ブロック、取引、コンセンサス、バリデータの関係を理解します。",
  "home.explore.title": "探究",
  "home.explore.description": "ウォレット、鍵、トークン、スマートコントラクト、DApps、ネットワークのつながりを学びます。",
  "home.practise.title": "実践",
  "home.practise.description": "体系的な説明と実例で各テーマの理解を深めます。",
  "home.features.practical.title": "実践的な学習",
  "home.features.web3.title": "WEB3に特化",
  "home.features.security.title": "セキュリティ重視",
  "home.features.community.title": "コミュニティへ",
  "home.about.label": "[ BIRTHDAY MESSAGINGについて ]",
  "home.about.title": "会社",
  "home.about.titleSpan": "ChainLabを支える会社。",
  "home.about.description": "ChainLabは、ブロックチェーンとWeb3を分かりやすくするためにBirthday Messagingが作った教育プロジェクトです。",
  "home.about.button": "CHAINLABを見る",
  "home.about.location": "教育 / テクノロジー / WEB3",
  "home.mission.label": "[ CHAINLABとは ]",
  "home.about.whyTitle": "Web3は変化しています。",
  "home.about.whyIntro": "ブロックチェーンは暗号資産だけではありません。所有権、デジタル資産、アプリ、コミュニティについて新しい考え方をもたらします。",
  "home.mission.fundamentals.title": "基礎から始める",
  "home.mission.connection.title": "つながりから学ぶ",
  "home.mission.risks.title": "リスクを理解する",
  "home.mission.builder.title": "ビルダーとして考える",
  "home.paths.label": "[ 学習パスを探す ]",
  "home.paths.chooseTopic": "テーマを選ぶ。",
  "home.paths.startJourney": "学習を始める。",
  "home.paths.viewAll": "すべてのモジュール →",
  "home.paths.startModule": "モジュールを開始 →",
  "home.paths.comingSoon": "近日公開",
  "home.paths.blockchain.title": "ブロックチェーン",
  "home.paths.solana.title": "SOLANA",
  "home.paths.memeCoins.title": "ミームコイン",
  "home.paths.security.title": "WEB3セキュリティ",
  "home.paths.tokenomics.title": "トークノミクス",
  "home.process.label": "[ CHAINLABの使い方 ]",
  "home.process.title": "シンプルな道筋で",
  "home.process.titleSpan": "Web3を学ぶ。",
  "home.process.choose.title": "選ぶ",
  "home.process.follow.title": "進む",
  "home.process.connect.title": "つなげる",
  "home.process.keep.title": "学び続ける",
  "home.security.label": "[ セキュリティ第一 ]",
  "home.security.title": "知識は",
  "home.security.titleSpan": "安全の一部です。",
  "home.security.button": "セキュリティを学ぶ →",
  "home.security.imageLabel": "署名前に確認",
  "home.faq.label": "[ よくある質問 ]",
  "home.faq.title": "質問がありますか？",
  "home.faq.titleSpan": "答えがあります。",
  "home.faq.free.question": "ChainLabは無料ですか？",
  "home.faq.experience.question": "事前の経験は必要ですか？",
  "home.faq.learn.question": "ChainLabでは何を学べますか？",
  "home.faq.investment.question": "ChainLabは投資プラットフォームですか？",
  "home.faq.creator.question": "ChainLabを作ったのは誰ですか？",
  "home.final.label": "[ 始める準備はできましたか？ ]",
  "home.final.title": "あなたのWeb3",
  "home.final.titleSpan": "学習の旅はここから始まります。",
  "home.final.description": "基礎から始め、知識を築き、技術を理解しましょう。",
  "footer.description": "Birthday Messagingが作った、ブロックチェーンとWeb3を分かりやすく学べる教育プラットフォーム。",
  "footer.tagline": "学ぶ。実践する。つくる。成長する。",
  "footer.learning": "学習",
  "footer.learn": "学ぶ",
  "footer.security": "セキュリティ",
  "footer.learningPaths": "学習パス",
  "footer.about": "概要",
  "footer.company": "会社"
};

const ko: TranslationDictionary = {
  "nav.blockchain": "블록체인",
  "nav.solana": "SOLANA",
  "nav.memeCoins": "밈 코인",
  "nav.security": "보안",
  "home.hero.eyebrow": "[ WEB3 교육 ]",
  "home.hero.learn": "배우고",
  "home.hero.build": "만들고",
  "home.hero.ownThe": "이해하는",
  "home.hero.future": "미래",
  "home.hero.description": "명확하고 체계적인 수업을 통해 블록체인, Solana, 밈 코인, 토크노믹스와 Web3 보안을 배워보세요.",
  "home.hero.startLearning": "학습 시작",
  "home.hero.exploreTopics": "주제 탐색",
  "home.hero.note": "블록체인 사전 경험이 필요하지 않습니다.",
  "home.overview.kicker": "[ 학습 개요 ]",
  "home.overview.title": "개념 하나씩 이해를 쌓아보세요.",
  "home.overview.intro": "기초부터 시작해 Web3를 구성하는 핵심 개념을 단계적으로 연결합니다.",
  "home.topics.kicker": "[ 핵심 주제 ]",
  "home.topics.intro": "Web3 생태계를 구성하는 기술, 개념과 위험을 알아보세요.",
  "home.topic.blockchain.title": "블록체인",
  "home.topic.blockchain.description": "분산 원장, 블록, 트랜잭션, 합의와 블록체인 네트워크의 작동 방식을 이해합니다.",
  "home.topic.blockchain.link": "블록체인 배우기",
  "home.topic.solana.title": "SOLANA",
  "home.topic.solana.description": "Solana의 구조, 계정, 프로그램, 트랜잭션, 검증자와 생태계를 살펴봅니다.",
  "home.topic.solana.link": "SOLANA 배우기",
  "home.topic.memeCoins.title": "밈 코인",
  "home.topic.memeCoins.description": "토큰, 커뮤니티, 유동성, 토크노믹스, 시장 움직임과 위험을 이해합니다.",
  "home.topic.memeCoins.link": "밈 코인 배우기",
  "home.topic.security.title": "보안",
  "home.topic.security.description": "지갑, 개인 키, 사기, 피싱, 스마트 계약과 안전한 Web3 사용을 배웁니다.",
  "home.topic.security.link": "보안 배우기",
  "home.topic.dapps.title": "DApps",
  "home.topic.dapps.description": "탈중앙화 앱이 사용자, 스마트 계약, 지갑과 블록체인 네트워크를 연결하는 방식을 알아봅니다.",
  "home.understand.title": "이해하기",
  "home.understand.description": "블록체인이 무엇이며 블록, 트랜잭션, 합의와 검증자가 어떻게 연결되는지 알아봅니다.",
  "home.explore.title": "탐색하기",
  "home.explore.description": "지갑, 키, 토큰, 스마트 계약, DApp과 네트워크의 연결을 살펴봅니다.",
  "home.practise.title": "연습하기",
  "home.practise.description": "구조화된 설명과 실제 예제로 각 주제에 대한 이해를 강화합니다.",
  "home.features.practical.title": "실용적인 학습",
  "home.features.web3.title": "WEB3 중심",
  "home.features.security.title": "보안 중심",
  "home.features.community.title": "커뮤니티 참여",
  "home.about.label": "[ BIRTHDAY MESSAGING 소개 ]",
  "home.about.title": "회사",
  "home.about.titleSpan": "ChainLab을 만든 팀.",
  "home.about.description": "ChainLab은 블록체인과 Web3를 쉽게 이해할 수 있도록 Birthday Messaging이 만든 교육 프로젝트입니다.",
  "home.about.button": "CHAINLAB 살펴보기",
  "home.about.location": "교육 / 기술 / WEB3",
  "home.mission.label": "[ 왜 CHAINLAB인가 ]",
  "home.about.whyTitle": "Web3는 변화하고 있습니다.",
  "home.about.whyIntro": "블록체인은 암호화폐 그 이상입니다. 소유권, 디지털 자산, 애플리케이션과 커뮤니티를 바라보는 새로운 방식을 제공합니다.",
  "home.mission.fundamentals.title": "기초부터 시작하기",
  "home.mission.connection.title": "연결을 통해 배우기",
  "home.mission.risks.title": "위험 이해하기",
  "home.mission.builder.title": "빌더처럼 생각하기",
  "home.paths.label": "[ 학습 경로 탐색 ]",
  "home.paths.chooseTopic": "주제를 선택하세요.",
  "home.paths.startJourney": "여정을 시작하세요.",
  "home.paths.viewAll": "모든 모듈 보기 →",
  "home.paths.startModule": "모듈 시작 →",
  "home.paths.comingSoon": "곧 공개",
  "home.paths.blockchain.title": "블록체인",
  "home.paths.solana.title": "SOLANA",
  "home.paths.memeCoins.title": "밈 코인",
  "home.paths.security.title": "WEB3 보안",
  "home.paths.tokenomics.title": "토크노믹스",
  "home.process.label": "[ CHAINLAB 이용 방법 ]",
  "home.process.title": "간단한 경로로",
  "home.process.titleSpan": "Web3 지식을 배웁니다.",
  "home.process.choose.title": "선택",
  "home.process.follow.title": "따라가기",
  "home.process.connect.title": "연결",
  "home.process.keep.title": "계속 배우기",
  "home.security.label": "[ 보안 우선 ]",
  "home.security.title": "지식은",
  "home.security.titleSpan": "보안의 일부입니다.",
  "home.security.button": "보안 배우기 →",
  "home.security.imageLabel": "서명하기 전에 확인",
  "home.faq.label": "[ 자주 묻는 질문 ]",
  "home.faq.title": "질문이 있나요?",
  "home.faq.titleSpan": "답변이 있습니다.",
  "home.faq.free.question": "ChainLab은 무료인가요?",
  "home.faq.experience.question": "사전 경험이 필요한가요?",
  "home.faq.learn.question": "ChainLab에서 무엇을 배울 수 있나요?",
  "home.faq.investment.question": "ChainLab은 투자 플랫폼인가요?",
  "home.faq.creator.question": "ChainLab은 누가 만들었나요?",
  "home.final.label": "[ 시작할 준비가 되었나요? ]",
  "home.final.title": "당신의 Web3",
  "home.final.titleSpan": "학습 여정은 여기서 시작됩니다.",
  "home.final.description": "기초부터 시작하고 지식을 쌓으며 기술을 이해하세요.",
  "footer.description": "블록체인과 Web3를 쉽게 이해할 수 있도록 Birthday Messaging이 만든 교육 플랫폼입니다.",
  "footer.tagline": "배우고. 연습하고. 만들고. 성장하세요.",
  "footer.learning": "학습",
  "footer.learn": "배우기",
  "footer.security": "보안",
  "footer.learningPaths": "학습 경로",
  "footer.about": "소개",
  "footer.company": "회사"
};

const translations: Record<Language, TranslationDictionary> = {
  en,
  tn,
  fr,
  es,
  pt,
  de,
  zh,
  ar,
  hi,
  sw,
  ja,
  ko,
};

const LanguageContext = createContext<LanguageContextValue | undefined>(
  undefined
);

export function LanguageProvider({
  children,
}: {
  children: ReactNode;
}) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);

    if (
      saved &&
      Object.prototype.hasOwnProperty.call(languageLabels, saved)
    ) {
      setLanguageState(saved as Language);
    }
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const setLanguage = useCallback((nextLanguage: Language) => {
    setLanguageState(nextLanguage);

    window.localStorage.setItem(
      LANGUAGE_STORAGE_KEY,
      nextLanguage
    );

    window.dispatchEvent(
      new CustomEvent("chainlab-language-change", {
        detail: {
          language: nextLanguage,
        },
      })
    );
  }, []);

  const t = useCallback(
    (key: string) => {
      const current = translations[language]?.[key];

      if (current !== undefined && current !== "") {
        return current;
      }

      const english = translations.en[key];

      if (english !== undefined && english !== "") {
        return english;
      }

      return key;
    },
    [language]
  );

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t,
    }),
    [language, setLanguage, t]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error(
      "useLanguage must be used inside LanguageProvider."
    );
  }

  return context;
}

export { languageLabels };
